import './Pages.css';
export default function IPOPage({ data, detailSlug }){
 const rows=data?.india?.rows||data?.calendar?.rows||[];
 const selected=rows.find(r=>slug(r.company||r.name||r.symbol)===detailSlug)||rows[0];
 if(detailSlug && !selected) return <div className="page"><div className="empty-page"><h1>IPO data not available</h1><p>This page is ready, but the configured provider has not returned this IPO.</p><a href="/ipo">Back to IPO</a></div></div>;
 return <div className="page"><div className="page__hero"><span>BAZAAR BRIEF · IPO</span><h1>{selected?.company||selected?.name||'Indian IPO Tracker'}</h1><p>Structured IPO facts, dates, issue details, subscription, financials and source links. Unavailable fields remain blank instead of being filled with old data.</p></div>{selected?<IPOFacts row={selected}/>:<div className="setup-card"><h3>Connect an IPO API</h3><p>GMP, subscription and allotment fields are provider-dependent. Missing values are shown as — rather than replaced with old data.</p></div>}<div className="detail-nav"><a href="/ipo-calendar">IPO Calendar</a><a href="/gmp">GMP</a><a href="/ipo-allotment-status">Allotment</a></div></div>
}
function IPOFacts({row:r}){const fields=[['Price band',r.price_band||r.priceRange||r.price||r.issue_price],['IPO dates',r.open_date&&r.close_date?`${r.open_date} → ${r.close_date}`:r.date],['Lot size',r.lot_size||r.lotSize],['Minimum investment',r.min_investment||r.minimum_investment],['Fresh issue / OFS',r.sale_type||r.fresh_issue||r.ofs],['Issue size',r.issue_size||r.issueSize],['GMP',r.gmp?.value||r.gmp,'Unofficial / market-reported'],['Subscription',r.subscription?.total||r.subscription_total||r.subscription],['Allotment date',r.allotment_date||r.allotmentDate],['Listing date',r.listing_date||r.listingDate],['Registrar',r.registrar],['Promoters',r.promoters],['Objects of issue',r.objects_of_issue||r.objects],['Revenue',r.revenue],['Profit',r.profit],['Debt',r.debt]];return <section className="facts"><div className="facts-grid">{fields.map(([label,value,note])=><div key={label}><span>{label}</span><strong>{value==null||value===''?'—':String(value)}</strong>{note&&<small>{note}</small>}</div>)}</div><p className="disclaimer">IPO fields are provider-dependent. GMP is unofficial and can change rapidly; it is not an exchange-set price.</p></section>}
function slug(s){return String(s||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
