import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const TWO_HOURS = 2 * 60 * 60 * 1000;
function clone(x){return JSON.parse(JSON.stringify(x))}
function money(n,dec=2){if(n===null||n===undefined||n===''||Number.isNaN(Number(n)))return '—';return new Intl.NumberFormat('en-IN',{maximumFractionDigits:dec,minimumFractionDigits:dec}).format(Number(n))}
function pct(n){return n===null||n===undefined||Number.isNaN(Number(n))?'—':`${Number(n)>=0?'+':''}${Number(n).toFixed(2)}%`}
function parseNum(v){const n=Number(v);return Number.isFinite(n)?n:0}
function bandHigh(band){const m=String(band||'').match(/([\d,.]+)\s*[–-]\s*([\d,.]+)/);return m?parseNum(m[2].replace(/,/g,'')):parseNum(String(band).replace(/[^\d.]/g,''))}
function slugify(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}

function useData(){
 const [data,setData]=useState(null);
 const [last,setLast]=useState(null);
 const [loading,setLoading]=useState(true);
 const [msg,setMsg]=useState('Loading live shared API data…');
 const refresh=async(manual=false)=>{
  setLoading(true);setMsg(manual?'Refreshing shared API data…':'Loading shared API data…');
  try{
   const r=await fetch(`/data/latest.json?t=${Date.now()}`,{cache:'no-store'});
   if(!r.ok)throw new Error(`Shared API dataset returned HTTP ${r.status}.`);
   const next=await r.json();
   if(!next || next.dataPolicy?.primary!=='API-only' || !next.market || next.refresh?.status!=='ok'){
    throw new Error('Live API dataset is unavailable or not marked API-only.');
   }
   const normalized={
    ...next,
    source: next.source || 'API-only shared scheduled feed',
    market: {
      ...(next.market||{}),
      indices: Array.isArray(next.market?.indices)?next.market.indices:[],
      global: Array.isArray(next.market?.global)?next.market.global:[],
      commodities: Array.isArray(next.market?.commodities)?next.market.commodities:[],
      stocks: Array.isArray(next.market?.stocks)?next.market.stocks:[]
    },
    fiiDii: next.fiiDii || {},
    ipo: {
      ...(next.ipo||{}),
      mainboard: Array.isArray(next.ipo?.mainboard)?next.ipo.mainboard:[],
      sme: Array.isArray(next.ipo?.sme)?next.ipo.sme:[]
    },
    news: Array.isArray(next.news)?next.news:[]
   };
   setData(normalized);setLast(normalized.updatedAt||null);setMsg('');
  }catch(e){
   setData(null);setLast(null);setMsg(e.message);
  }finally{setLoading(false)}
 };
 useEffect(()=>{
  refresh(false);
  const timer=setInterval(()=>refresh(false),TWO_HOURS);
  const vis=()=>{if(document.visibilityState==='visible')refresh(false)};
  document.addEventListener('visibilitychange',vis);
  return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',vis)}
 },[]);
 return {data,last,loading,msg,refresh}
}
function fmtDate(value){return value?new Date(value).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—'}
function Sparkline({positive=true,seed=1}){const points=Array.from({length:12},(_,i)=>{const wave=Math.sin((i+seed)*0.85)*3;const drift=(positive?i:-i)*0.65;return 28-wave-drift});const min=Math.min(...points),max=Math.max(...points);const d=points.map((v,i)=>`${i*9},${18-((v-min)/(max-min||1))*14}`).join(' ');return <svg className={`spark ${positive?'sparkUp':'sparkDown'}`} viewBox="0 0 99 36" preserveAspectRatio="none" aria-hidden="true"><polyline points={d} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Header({state,onNav}){const [searchOpen,setSearchOpen]=useState(false);return <><header className="appHeader"><button className="brand" onClick={()=>onNav('/')} aria-label="Bazaar Brief home"><span className="brandMark">B</span><span>BAZAAR<span>BRIEF</span></span></button><div className="marketLive"><i></i><span>MARKET DATA</span><b>API feed</b></div><nav className="mainNav" aria-label="Primary navigation"><button className="active" onClick={()=>onNav('/')}>Markets</button><button onClick={()=>onNav('/ipo')}>IPOs</button><button onClick={()=>onNav('/gmp')}>GMP Tracker</button><button onClick={()=>onNav('/ipo-allotment-status')}>Allotment</button><button onClick={()=>onNav('/tools')}>Tools</button></nav><div className="headerActions"><button className="searchBtn" onClick={()=>setSearchOpen(v=>!v)}>⌘ K <span>Search</span></button><button className="refreshBtn" onClick={()=>state.refresh(true)} disabled={state.loading}>{state.loading?'Refreshing':'Refresh'}</button></div></header>{searchOpen&&<div className="searchPanel"><input autoFocus placeholder="Search IPOs, tools, markets…" onKeyDown={e=>{if(e.key==='Escape')setSearchOpen(false)}}/><span>Press Esc to close</span></div>}<div className="dataRail"><span><i className="pulseDot"></i> {state.data?.source || 'Waiting for shared API feed'}</span><span>Updated {fmtDate(state.last)}</span><span>Auto refresh · 2h</span></div></>}
function Section({title,sub,action,children}){return <section className="dashSection"><div className="sectionHead"><div><div className="sectionKicker">{title}</div>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
function IndexCard({x,index}){const positive=(x.pct??0)>=0;return <article className={`indexCard ${x.name==='GIFT NIFTY'?'featured':''}`}><div className="indexTop"><span>{x.name}</span><em>{x.name==='GIFT NIFTY'?'FUTURES':'INDEX'}</em></div><div className="indexValue">{money(x.value, x.value>=10000?2:2)}</div><div className="indexBottom"><span className={positive?'gain':'loss'}>{x.change==null?'Live quote':`${x.change>=0?'+':''}${money(x.change,2)} · ${pct(x.pct)}`}</span><Sparkline positive={positive} seed={index+1}/></div>{x.note&&<small className="indexNote">{x.note}</small>}</article>}
function IndexCards({items}){return <div className="indexBento">{items.map((x,i)=><IndexCard key={x.name} x={x} index={i}/>)}</div>}
function Home({data,navigate}){const m=data.market;const gain=[...m.stocks].sort((a,b)=>b.pct-a.pct).slice(0,5),lose=[...m.stocks].sort((a,b)=>a.pct-b.pct).slice(0,5);const commodities=m.commodities||[];return <main className="dashboard">
 <section className="heroPanel"><div className="heroCopy"><div className="eyebrow"><span></span>BAZAARBRIEF / DAILY MARKET INTELLIGENCE</div><h1>Everything moving<br/><strong>Indian markets.</strong></h1><p>One shared market feed for Nifty 50, Sensex, GIFT Nifty, IPOs, institutional flows and global cues.</p><div className="heroMeta"><span>● Shared data cache</span><span>Last sync {fmtDate(data.updatedAt)}</span><span>Next sync within 2h</span></div></div><div className="heroPulse"><div className="pulseHeader"><span>MARKET PULSE</span><b>28 SEP</b></div><div className="pulseValue">{data.fiiDii.fii<0?'Risk-off':'Risk-on'}</div><p>Indian equities closed under pressure while crude and global risk cues remain key drivers.</p><div className="pulseStats"><div><small>FII NET</small><strong className="loss">₹{money(Math.abs(data.fiiDii.fii),0)} Cr</strong></div><div><small>DII NET</small><strong className="gain">₹{money(data.fiiDii.dii,0)} Cr</strong></div></div></div></section>
 <Section title="Indian market" sub="Cash-market close + GIFT Nifty futures indicator"><IndexCards items={m.indices}/></Section>
 <Section title="5 things moving the market" sub="Fast context, source-stamped"><div className="storyGrid">{data.news.slice(0,5).map((n,i)=><article className="storyCard" key={i}><div className="storyTop"><span>{n.tag}</span><small>{n.age}</small></div><h3>{n.title}</h3><footer>{n.source}<span>↗</span></footer></article>)}</div></Section>
 <Section title="Market movers" sub="Largest percentage moves in the API stock feed"><div className="splitPanel"><MoverTable title="Top gainers" rows={gain}/><MoverTable title="Top losers" rows={lose}/></div></Section>
 <Section title="Institutional flow" sub={`Cash market · ${data.fiiDii.date}`}><div className="flowGrid"><div className="flowCard"><div><span>FII / FPI NET</span><b className="loss">₹{money(Math.abs(data.fiiDii.fii),0)} Cr</b><small>Net selling</small></div><div className="flowIcon loss">↓</div></div><div className="flowCard"><div><span>DII NET</span><b className="gain">₹{money(data.fiiDii.dii,0)} Cr</b><small>Net buying</small></div><div className="flowIcon gain">↑</div></div></div></Section>
 <Section title="Global + commodities" sub="All values from the shared API dataset · no static market values"><div className="assetGrid">{m.global.map((x,i)=><AssetCard key={x.name} x={x} seed={i} fx={commodities.find(c=>c.name==='USD/INR')?.value}/>)}{commodities.map((x,i)=><AssetCard key={x.name} x={x} seed={i+5} commodity fx={commodities.find(c=>c.name==='USD/INR')?.value}/>)}</div><div className="sourceNote">All displayed market values come from the shared API dataset. The browser does not call financial providers directly. If the scheduled API refresh fails, the UI shows no financial data rather than presenting a bundled snapshot.</div></Section>
 <Section title="IPO pipeline" sub="Mainboard and SME separated"><div className="ipoDashboard"><IPOPipeline title="Mainboard" items={data.ipo.mainboard.filter(x=>x.status==='Open').slice(0,3)} navigate={navigate}/><IPOPipeline title="SME" items={data.ipo.sme.filter(x=>x.status==='Open').slice(0,3)} navigate={navigate}/></div></Section>
 <Section title="Financial tools" sub="Instant, formula-based calculators"><div className="toolTiles">{Object.entries(TOOL_DEFS).slice(0,12).map(([k,t])=><button key={k} onClick={()=>navigate('/tools/'+k)}><span>{t.title}</span><b>↗</b></button>)}</div></Section>
 </main>}
function MoverTable({title,rows}){return <div className="dataPanel"><div className="panelTitle"><h3>{title}</h3><span>{rows.length} names</span></div>{rows.map(x=><div className="moverRow" key={x.symbol}><div className="stockAvatar">{x.symbol.slice(0,2)}</div><div className="stockName"><b>{x.symbol}</b><small>{x.name}</small></div><strong>₹{money(x.price)}</strong><span className={x.pct>=0?'gain':'loss'}>{pct(x.pct)}</span></div>)}</div>}
function AssetCard({x,seed,commodity=false,fx}){const positive=(x.pct??0)>=0;const precious=x.displayValue!=null;const display=precious?`₹${money(x.displayValue,0)}`:(x.name==='USD/INR'?`₹${money(x.value,2)}`:`${x.unit?.startsWith('$')?'$':''}${money(x.value, x.name==='NATURAL GAS'?4:2)}`);return <article className="assetCard"><div className="assetTop"><span>{x.name}</span><em>{precious?x.displayUnit:(commodity?(x.unit||'MARKET'):'INDEX')}</em></div><strong>{display}</strong><div className="assetBottom"><span className={positive?'gain':'loss'}>{pct(x.pct)}</span><Sparkline positive={positive} seed={seed}/></div>{precious&&<small className="assetSub">{x.conversion==='direct INR API'?'Direct INR API':'Live USD spot × live USD/INR'} · {x.displayUnit}</small>}<small className="assetAsOf">{x.asOf||'API feed'} · {x.source||'API feed'}</small></article>}
function IPOPipeline({title,items,navigate}){return <div className="ipoPipeline"><div className="panelTitle"><h3>{title} IPO</h3><button onClick={()=>navigate('/ipo/'+title.toLowerCase())}>View all →</button></div>{items.length?items.map(x=><div className="pipelineRow" key={x.slug}><div className="ipoIdentity"><div className="ipoLogo">{x.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</div><div><b>{x.name}</b><small>{x.band} · Lot {money(x.lot,0)}</small></div></div><div className="subRadar"><span>QIB {x.qib}</span><i><em style={{width:`${Math.min(100,parseNum(x.qib)*18)}%`}}></em></i><small>Retail {x.retail}</small></div><div className="gmpChip"><small>GMP*</small><b>{x.gmp==null?'—':`₹${money(x.gmp,0)}`}</b></div></div>):<div className="emptyState">No open {title} IPOs in the shared dataset.</div>}</div>}
function Row({x}){return <div className="row"><div><b>{x.symbol}</b><small>{x.name}</small></div><strong>₹{money(x.price)}</strong><span className={x.pct>=0?'gain':'loss'}>{pct(x.pct)}</span></div>}
function IPOCard({x,navigate}){const g=x.gmp===null||x.gmp===undefined?'—':`₹${money(x.gmp,0)}`;const listing=x.gmp!==null&&x.gmp!==undefined?`₹${money(bandHigh(x.band)+x.gmp)}`:'—';return <article className="ipoCard"><div className="ipoTop"><span>{x.type}</span><b>{x.status}</b></div><h3>{x.name}</h3><p>{x.band} · Lot {money(x.lot,0)}</p><div className="ipoMeta"><div><small>Issue</small><b>{x.issue}</b></div><div><small>Close</small><b>{x.close}</b></div><div><small>GMP*</small><b>{g}</b></div></div><div className="ipoMeta"><div><small>Subscription</small><b>{x.subscription}</b></div><div><small>Min. invest.</small><b>₹{money(x.min,0)}</b></div><div><small>GMP est.</small><b>{listing}</b></div></div><button onClick={()=>navigate('/ipo/'+x.type.toLowerCase()+'/'+x.slug)}>View IPO →</button></article>}
function allIPOs(data){return [...data.ipo.mainboard,...data.ipo.sme]}
function IPOPage({data,kind,slug,navigate}){const list=kind==='mainboard'?data.ipo.mainboard:kind==='sme'?data.ipo.sme:allIPOs(data);if(slug){const x=allIPOs(data).find(i=>i.slug===slug)||list[0];return <main className="page"><div className="pageTitle"><span>{x.type.toUpperCase()} IPO · {x.status}</span><h1>{x.name}</h1><p>Source-dated issue data. GMP is unofficial and market-reported.</p></div><div className="detailGrid">{[['Status',x.status],['Price band',x.band],['Face value',x.faceValue],['IPO dates',`${x.open} → ${x.close}`],['Lot size',x.lot+' shares'],['Minimum investment',`₹${money(x.min,0)}`],['Issue size',x.issue],['Fresh issue',x.fresh],['OFS',x.ofs],['Subscription',x.subscription],['QIB',x.qib],['NII / HNI',x.nii],['Retail / Individual',x.retail],['GMP*',x.gmp===null?'Not reported':`₹${money(x.gmp,0)}`],['GMP updated',x.gmpUpdated||'—'],['Indicative listing price*',x.gmp===null?'—':`₹${money(bandHigh(x.band)+x.gmp)}`],['Allotment',x.allotment],['Refund',x.refund],['Demat credit',x.credit],['Listing',x.listing],['Exchange',x.exchange],['Registrar',x.registrar],['Lead manager(s)',x.leadManagers]].map(([a,b])=><div className="detail" key={a}><small>{a}</small><strong>{b||'—'}</strong></div>)}</div><div className="two"><div className="panel"><h2>Financial results</h2><RowText a="Revenue" b={x.revenue}/><RowText a="Profit / PAT" b={x.profit}/><RowText a="Debt / borrowings" b={x.debt}/><RowText a="Promoters" b={x.promoters}/></div><div className="panel"><h2>Issue purpose</h2><p className="longText">{x.objects}</p><RowText a="Sector" b={x.sector}/><RowText a="Source" b={x.source}/><RowText a="Source date" b={x.sourceDate}/></div></div><div className="panel"><h2>GMP disclosure</h2><p className="longText">GMP is an unofficial grey-market quote. It is not exchange-published, may vary between trackers and can change rapidly. The indicative listing price above is only the arithmetic of upper price band + reported GMP; it is not a forecast or guarantee.</p></div><button className="back" onClick={()=>navigate(kind?`/ipo/${kind}`:'/ipo')}>← Back to {kind||'all IPOs'}</button></main>}
 return <main className="page"><div className="pageTitle"><span>{kind?kind.toUpperCase()+' IPO':'IPO'}</span><h1>{kind==='mainboard'?'Mainboard IPOs':kind==='sme'?'SME IPOs':'Indian IPOs'}</h1><p>{kind==='mainboard'?'Mainboard issues with price, lot, subscription, GMP and key company fields.':kind==='sme'?'SME issues with higher lot/application requirements shown separately.':'Mainboard and SME IPOs, separated for easier discovery.'}</p></div><div className="ipoTabs"><button onClick={()=>navigate('/ipo/mainboard')}>Mainboard</button><button onClick={()=>navigate('/ipo/sme')}>SME</button><button onClick={()=>navigate('/ipo')}>All</button></div><div className="ipoGrid">{list.map(x=><IPOCard x={x} key={x.slug} navigate={navigate}/>)}</div></main>}
function RowText({a,b}){return <div className="rowText"><span>{a}</span><b>{b}</b></div>}
function Calendar({data,navigate}){const rows=allIPOs(data);return <main className="page"><div className="pageTitle"><span>CALENDAR</span><h1>IPO Calendar</h1><p>Open, close, allotment, refund, credit and listing dates.</p></div><div className="ipoTabs"><button onClick={()=>navigate('/ipo/mainboard')}>Mainboard</button><button onClick={()=>navigate('/ipo/sme')}>SME</button></div><div className="tableWrap"><table><thead><tr><th>IPO</th><th>Type</th><th>Status</th><th>Open</th><th>Close</th><th>Allotment</th><th>Listing</th><th>Price</th><th>Lot</th><th>GMP</th></tr></thead><tbody>{rows.map(x=><tr key={x.slug}><td><b>{x.name}</b><small>{x.symbol}</small></td><td>{x.type}</td><td>{x.status}</td><td>{x.open}</td><td>{x.close}</td><td>{x.allotment}</td><td>{x.listing}</td><td>{x.band}</td><td>{x.lot}</td><td>{x.gmp===null?'—':'₹'+money(x.gmp,0)}</td></tr>)}</tbody></table></div></main>}
function GMP({data}){const rows=allIPOs(data);return <main className="page"><div className="pageTitle"><span>UNOFFICIAL · SOURCE DATED</span><h1>IPO GMP Today</h1><p>Latest reported grey-market premium. GMP is unofficial and can differ across trackers.</p></div><div className="tableWrap"><table><thead><tr><th>IPO</th><th>Type</th><th>Upper band</th><th>GMP</th><th>Indicative price*</th><th>GMP %</th><th>Subscription</th><th>GMP as of</th></tr></thead><tbody>{rows.map(x=>{const hi=bandHigh(x.band);const g=x.gmp;return <tr key={x.slug}><td><b>{x.name}</b></td><td>{x.type}</td><td>₹{money(hi,2)}</td><td className={g>0?'gain':'loss'}>{g===null?'Not reported':'₹'+money(g,0)}</td><td>{g===null?'—':'₹'+money(hi+g,2)}</td><td>{g===null?'—':pct(g/hi*100)}</td><td>{x.subscription}</td><td>{x.gmpUpdated||'—'}</td></tr>})}</tbody></table></div></main>}
function Allotment({data}){return <main className="page"><div className="pageTitle"><span>ALLOTMENT</span><h1>IPO Allotment Status</h1><p>Expected basis-of-allotment dates and official verification route.</p></div><div className="ipoGrid">{allIPOs(data).map(x=><div className="panel" key={x.slug}><h2>{x.name}</h2><RowText a="Status" b={x.status}/><RowText a="Allotment" b={x.allotment}/><RowText a="Refund" b={x.refund}/><RowText a="Demat credit" b={x.credit}/><RowText a="Listing" b={x.listing}/><a className="external" href="https://www.nseindia.com/check-trades-bids-verify-ipo-bids" target="_blank" rel="noreferrer">Official NSE IPO bid/allotment check ↗</a></div>)}</div></main>}

const TOOL_DEFS={
 sip:{title:'SIP Calculator',fields:[['monthly','Monthly investment (₹)',5000],['rate','Expected annual return (%)',12],['years','Investment period (years)',10]],calc:v=>{const p=Math.max(0,parseNum(v.monthly)),r=parseNum(v.rate)/1200,n=Math.max(0,parseNum(v.years))*12,fv=r? p*((Math.pow(1+r,n)-1)/r)*(1+r):p*n,invested=p*n;return [['Invested',`₹${money(invested,0)}`],['Estimated value',`₹${money(fv,0)}`],['Estimated gain',`₹${money(fv-invested,0)}`]]}},
 cagr:{title:'CAGR Calculator',fields:[['initial','Initial value (₹)',100000],['final','Final value (₹)',250000],['years','Years',5]],calc:v=>{const i=parseNum(v.initial),f=parseNum(v.final),y=parseNum(v.years);if(i<=0||f<0||y<=0)return [['CAGR','Enter positive values']];return [['CAGR',`${((Math.pow(f/i,1/y)-1)*100).toFixed(2)}%`]]}},
 average:{title:'Stock Average Calculator',fields:[['qty1','First quantity',100],['price1','First buy price (₹)',100],['qty2','Second quantity',100],['price2','Second buy price (₹)',80]],calc:v=>{const q1=Math.max(0,parseNum(v.qty1)),q2=Math.max(0,parseNum(v.qty2)),cost=q1*parseNum(v.price1)+q2*parseNum(v.price2),qty=q1+q2;return [['Total quantity',money(qty,0)],['Average price',qty?`₹${money(cost/qty)}`:'—'],['Total cost',`₹${money(cost,0)}`]]}},
 dividend:{title:'Dividend Calculator',fields:[['shares','Shares owned',100],['dividend','Dividend per share (₹)',10],['tax','Tax / withholding (%)',0]],calc:v=>{const gross=Math.max(0,parseNum(v.shares))*Math.max(0,parseNum(v.dividend)),tax=Math.max(0,parseNum(v.tax))*gross/100;return [['Gross dividend',`₹${money(gross,2)}`],['Tax',`₹${money(tax,2)}`],['Net dividend',`₹${money(gross-tax,2)}`]]}},
 pe:{title:'P/E Calculator',fields:[['price','Share price (₹)',500],['eps','EPS (₹)',25]],calc:v=>{const e=parseNum(v.eps);return [['P/E ratio',e>0?`${(parseNum(v.price)/e).toFixed(2)}x`:'—']]}},
 eps:{title:'EPS Calculator',fields:[['profit','Net profit (₹)',10000000],['shares','Weighted average shares',1000000]],calc:v=>{const s=parseNum(v.shares);return [['EPS',s>0?`₹${money(parseNum(v.profit)/s,2)}`:'—']]}},
 roe:{title:'ROE Calculator',fields:[['profit','Net profit (₹)',10000000],['equity','Average shareholders equity (₹)',50000000]],calc:v=>{const e=parseNum(v.equity);return [['ROE',e>0?`${(parseNum(v.profit)/e*100).toFixed(2)}%`:'—']]}},
 roce:{title:'ROCE Calculator',fields:[['ebit','EBIT (₹)',12000000],['capital','Capital employed (₹)',80000000]],calc:v=>{const c=parseNum(v.capital);return [['ROCE',c>0?`${(parseNum(v.ebit)/c*100).toFixed(2)}%`:'—']]}},
 marketcap:{title:'Market Cap Calculator',fields:[['price','Share price (₹)',500],['shares','Shares outstanding',10000000]],calc:v=>{const cap=parseNum(v.price)*parseNum(v.shares);return [['Market cap (₹)',`₹${money(cap,0)}`],['Market cap (₹ Cr)',`₹${money(cap/10000000,2)} Cr`]]}},
 profitgrowth:{title:'Profit Growth Calculator',fields:[['old','Previous profit (₹)',10000000],['new','Current profit (₹)',13000000]],calc:v=>{const o=parseNum(v.old);return [['Profit growth',o!==0?`${((parseNum(v.new)-o)/Math.abs(o)*100).toFixed(2)}%`:'—']]}},
 ipoinvestment:{title:'IPO Investment Calculator',fields:[['lot','Shares per lot',100],['price','IPO price per share (₹)',500],['lots','Number of lots',1]],calc:v=>{const lot=Math.max(0,parseNum(v.lot)),lots=Math.max(0,parseNum(v.lots)),inv=lot*parseNum(v.price)*lots;return [['Total shares',money(lot*lots,0)],['Investment',`₹${money(inv,0)}`]]}},
 ipoprofit:{title:'IPO Profit Calculator',fields:[['shares','Shares allotted',100],['buy','IPO price (₹)',500],['sell','Listing / sale price (₹)',650],['costs','Taxes + charges (₹)',0]],calc:v=>{const shares=Math.max(0,parseNum(v.shares)),buy=parseNum(v.buy),sell=parseNum(v.sell),costs=Math.max(0,parseNum(v.costs)),gross=(sell-buy)*shares,net=gross-costs;return [['Gross profit',`₹${money(gross,0)}`],['Costs',`₹${money(costs,0)}`],['Net profit',`₹${money(net,0)}`],['Return',buy>0?`${((sell-buy)/buy*100).toFixed(2)}%`:'—']]}},
 ipogmp:{title:'IPO GMP Calculator',fields:[['ipo','Upper price band (₹)',500],['gmp','GMP (₹)',80]],calc:v=>{const price=parseNum(v.ipo),g=parseNum(v.gmp);return [['Indicative listing price',`₹${money(price+g,2)}`],['Indicative premium',price?`${(g/price*100).toFixed(2)}%`:'—']]}},
 allotment:{title:'IPO Allotment Estimate',fields:[['applications','Applications received',100000],['lots','Lots available',5000]],calc:v=>{const a=Math.max(0,parseNum(v.applications)),l=Math.max(0,parseNum(v.lots));const p=a?Math.min(100,l/a*100):0;return [['Simple mathematical estimate',`${p.toFixed(2)}%`],['Disclaimer','Not a prediction; actual allotment follows category rules and registrar lottery/process.']]}},
 usd:{title:'USD / INR Converter',fields:[['usd','USD amount',100],['rate','USD/INR rate',96]],calc:v=>[['INR value',`₹${money(parseNum(v.usd)*parseNum(v.rate),2)}`]]},
 emi:{title:'EMI Calculator',fields:[['principal','Loan amount (₹)',1000000],['rate','Annual interest (%)',8.5],['years','Tenure (years)',10]],calc:v=>{const p=parseNum(v.principal),r=parseNum(v.rate)/1200,n=parseNum(v.years)*12;const emi=r? p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):(n?p/n:0);return [['Monthly EMI',`₹${money(emi,0)}`],['Total payment',`₹${money(emi*n,0)}`],['Total interest',`₹${money(emi*n-p,0)}`]]}},
 lumpsum:{title:'Lumpsum Calculator',fields:[['principal','Initial investment (₹)',100000],['rate','Expected annual return (%)',12],['years','Years',10]],calc:v=>{const p=parseNum(v.principal),r=parseNum(v.rate)/100,y=parseNum(v.years),fv=p*Math.pow(1+r,y);return [['Invested',`₹${money(p,0)}`],['Future value',`₹${money(fv,0)}`],['Gain',`₹${money(fv-p,0)}`]]}}
};
function Calculator({def}){const initial=Object.fromEntries(def.fields.map(([k,,v])=>[k,v]));const [v,setV]=useState(initial);useEffect(()=>setV(initial),[def.title]);const result=useMemo(()=>def.calc(v),[def,v]);return <div className="calculator"><h2>{def.title}</h2><div className="fieldGrid">{def.fields.map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="any" value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})}/></label>)}</div><div className="results">{result.map(([a,b])=><div className="resultRow" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></div>}
function Tools({tool}){const [active,setActive]=useState(tool&&TOOL_DEFS[tool]?tool:'sip');return <main><div className="pageTitle"><span>TOOLS</span><h1>Financial Tools</h1><p>Formula-based browser calculators with validation and instant results.</p></div><div className="toolSelector">{Object.entries(TOOL_DEFS).map(([k,d])=><button className={active===k?'active':''} key={k} onClick={()=>setActive(k)}>{d.title}</button>)}</div><Calculator def={TOOL_DEFS[active]}/><div className="toolNote"><b>Important:</b> calculators are mathematical tools, not investment advice. IPO GMP is unofficial; allotment estimation is not a prediction.</div></main>}
function Footer(){return <footer>BAZAAR BRIEF · Market data can be delayed. GIFT Nifty is a futures/pre-market indicator, not NIFTY 50 spot. GMP is unofficial / market-reported. Verify important figures against NSE/BSE, registrar pages and official IPO documents.</footer>}
class ErrorBoundary extends React.Component{
 constructor(props){super(props);this.state={error:null}}
 static getDerivedStateFromError(error){return {error}}
 componentDidCatch(error,info){console.error('BazaarBrief render error',error,info)}
 render(){
  if(this.state.error){
   return <><header className="appHeader"><button className="brand" onClick={()=>location.reload()}><span className="brandMark">B</span><span>BAZAAR<span>BRIEF</span></span></button><div className="marketLive"><i></i><span>APPLICATION</span><b>Error recovery</b></div></header><main className="emptyFeed"><div className="emptyFeedCard"><div className="eyebrow"><span></span>BAZAARBRIEF / RECOVERY</div><h1>The dashboard hit a rendering error.</h1><p>The application is still loaded, but a UI component failed while rendering. Reload the page to recover. No financial snapshot is being substituted.</p><button className="refreshBtn" onClick={()=>location.reload()}>Reload dashboard</button></div></main><Footer/></>;
  }
  return this.props.children;
 }
}
function App(){const state=useData();const [path,setPath]=useState(location.pathname.replace(/\/$/,'')||'/');const nav=p=>{history.pushState({},'',p);setPath(p);window.scrollTo({top:0,behavior:'smooth'})};useEffect(()=>{const f=()=>setPath(location.pathname.replace(/\/$/,'')||'/');addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);let content;if(!state.data){content=<main className="emptyFeed"><div className="emptyFeedCard"><div className="eyebrow"><span></span>LIVE SHARED DATA</div><h1>Waiting for the latest API refresh.</h1><p>Nothing is shown from a bundled snapshot. The page will display market, commodity, IPO, GMP, FII/DII and news data only after the scheduled API feed has completed successfully.</p><button className="refreshBtn" onClick={()=>state.refresh(true)} disabled={state.loading}>{state.loading?'Refreshing…':'Try again'}</button></div></main>}else if(path==='/ipo')content=<IPOPage data={state.data} navigate={nav}/>;else if(path==='/ipo/mainboard')content=<IPOPage data={state.data} kind="mainboard" navigate={nav}/>;else if(path==='/ipo/sme')content=<IPOPage data={state.data} kind="sme" navigate={nav}/>;else if(path.startsWith('/ipo/mainboard/'))content=<IPOPage data={state.data} kind="mainboard" slug={path.split('/')[3]} navigate={nav}/>;else if(path.startsWith('/ipo/sme/'))content=<IPOPage data={state.data} kind="sme" slug={path.split('/')[3]} navigate={nav}/>;else if(path==='/ipo-calendar')content=<Calendar data={state.data} navigate={nav}/>;else if(path==='/gmp')content=<GMP data={state.data}/>;else if(path==='/ipo-allotment-status')content=<Allotment data={state.data}/>;else if(path.startsWith('/tools/'))content=<Tools tool={path.split('/')[2]}/>;else if(path==='/tools')content=<Tools/>;else content=<Home data={state.data} navigate={nav}/>;return <><Header state={state} onNav={nav}/>{state.msg&&<div className="notice">{state.msg}</div>}{content}<Footer/></>}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
