import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const TWO_HOURS=2*60*60*1000;
const SNAPSHOT_DATE='28 Sep 2026';
const DATA_AS_OF='28 Sep 2026 · Indian market close / IPO data through 5:57 PM IST';

const SEED={
 updatedAt:'2026-09-28T17:57:00+05:30',
 source:'Verified dated snapshot · 28 Sep 2026',
 market:{
  indices:[
   {name:'NIFTY 50',value:22780.25,change:-360.25,pct:-1.56,kind:'index'},
   {name:'SENSEX',value:72771.72,change:-1124.02,pct:-1.52,kind:'index'},
   {name:'BANK NIFTY',value:54471.65,change:-1108.75,pct:-1.99,kind:'index'},
   {name:'GIFT NIFTY',value:22825.50,change:null,pct:null,kind:'gift',note:'Futures / overnight indicator; quote is separate from NIFTY spot'}
  ],
  global:[
   {name:'S&P 500',value:7785.76,change:-13.31,pct:-0.17,unit:'',asOf:'28 Sep'},
   {name:'NASDAQ 100',value:30046.14,change:-39.00,pct:-0.13,unit:'',asOf:'28 Sep'},
   {name:'FTSE 100',value:10822.13,change:-8.67,pct:-0.08,unit:'',asOf:'28 Sep'},
   {name:'HANG SENG',value:25303.41,change:186.22,pct:0.74,unit:'',asOf:'28 Sep'}
  ],
  commodities:[
   {name:'USD/INR',value:96.083,unit:'₹',pct:0.17},
   {name:'GOLD SPOT',value:4226.17,unit:'$',pct:-2.19},
   {name:'BRENT',value:98.72,unit:'$',pct:1.30},
   {name:'WTI',value:93.77,unit:'$',pct:1.48}
  ],
  stocks:[
   {symbol:'DRREDDY',name:"Dr. Reddy's Laboratories",price:1221,pct:1.67},
   {symbol:'INFY',name:'Infosys',price:1003.20,pct:0.30},
   {symbol:'HDFCLIFE',name:'HDFC Life',price:531.60,pct:0.11},
   {symbol:'TMPV',name:'Tata Motors Passenger Vehicles',price:281.75,pct:-3.00},
   {symbol:'ADANIENT',name:'Adani Enterprises',price:2831.10,pct:-2.93},
   {symbol:'JIOFIN',name:'Jio Financial Services',price:220.50,pct:-2.86},
   {symbol:'POWERGRID',name:'Power Grid',price:262.10,pct:-2.84},
   {symbol:'LT',name:'Larsen & Toubro',price:3775,pct:-2.83}
  ]
 },
 fiiDii:{date:'28 Sep 2026',fii:-5353.22,dii:5189.02,source:'NSE cash-segment aggregate'},
 ipo:{
  mainboard:[
   {name:'Moneyview Limited',slug:'moneyview-ipo',type:'Mainboard',symbol:'MONEYVIEW',status:'Closed',open:'24 Sep 2026',close:'28 Sep 2026',allotment:'29 Sep 2026',refund:'30 Sep 2026',credit:'30 Sep 2026',listing:'01 Oct 2026',band:'₹32–₹34',faceValue:'₹1',lot:441,min:14994,issue:'₹1,091.68 Cr',fresh:'₹750 Cr',ofs:'₹341.68 Cr',freshShares:'22.06 Cr shares',ofsShares:'10.05 Cr shares',subscription:'101.87x',qib:'230.54x',nii:'120.37x',retail:'20.41x',gmp:12,gmpUpdated:'28 Sep 2026',gmpSource:'IPO Ji / grey-market trackers',sector:'Fintech / consumer lending',exchange:'BSE, NSE',registrar:'MUFG Intime India Pvt. Ltd.',leadManagers:'Axis Capital Ltd.; BofA Securities India Ltd.; IIFL Capital Services Ltd.; Kotak Mahindra Capital Co. Ltd.',promoters:'As disclosed in RHP',revenue:'₹3,404.27 Cr (FY26)',profit:'₹242.71 Cr (FY26)',debt:'See latest RHP balance sheet',objects:'Fresh issue proceeds for business/capital requirements; general corporate purposes as detailed in RHP.',source:'IPO Ji / NSE-BSE compiled data',sourceDate:'28 Sep 2026 17:54 IST'},
   {name:'A-One Steels India Limited',slug:'a-one-steels-ipo',type:'Mainboard',symbol:'AONESTEEL',status:'Closed',open:'24 Sep 2026',close:'28 Sep 2026',allotment:'29 Sep 2026',refund:'30 Sep 2026',credit:'30 Sep 2026',listing:'01 Oct 2026',band:'₹385–₹405',faceValue:'₹10',lot:37,min:14985,issue:'₹405 Cr',fresh:'₹355 Cr',ofs:'₹50 Cr',freshShares:'87.65 lakh shares',ofsShares:'12.35 lakh shares',subscription:'12.22x',qib:'7.69x',nii:'25.80x',retail:'9.09x',gmp:24,gmpUpdated:'28 Sep 2026 17:30 IST',gmpSource:'IPO Ji',sector:'Steel',exchange:'BSE, NSE',registrar:'Bigshare Services Pvt. Ltd.',leadManagers:'PL Capital Markets Pvt. Ltd.; Khambatta Securities Ltd.',promoters:'As disclosed in RHP',revenue:'₹4,167.33 Cr (FY26)',profit:'₹127.41 Cr (FY26)',debt:'Borrowings are an object of the fresh issue',objects:'Pre-payment or partial repayment of certain outstanding borrowings; general corporate purposes.',source:'IPO Ji / Groww / exchange data',sourceDate:'28 Sep 2026 17:57 IST'},
   {name:'German Green Steel & Power Limited',slug:'german-green-steel-and-power-ipo',type:'Mainboard',symbol:'GERMAN',status:'Open',open:'25 Sep 2026',close:'29 Sep 2026',allotment:'30 Sep 2026',refund:'01 Oct 2026',credit:'01 Oct 2026',listing:'06 Oct 2026',band:'₹132–₹139',faceValue:'₹10',lot:107,min:14873,issue:'₹303.90 Cr',fresh:'₹290 Cr',ofs:'₹13.90 Cr',freshShares:'2.09 Cr shares',ofsShares:'10 lakh shares',subscription:'5.39x',qib:'1.40x',nii:'8.22x',retail:'6.46x',gmp:26,gmpUpdated:'28 Sep 2026 19:00 IST',gmpSource:'IPO Guru / IPO Ji',sector:'Steel / power',exchange:'BSE, NSE',registrar:'Bigshare Services Pvt. Ltd.',leadManagers:'Systematix Corporate Services Ltd.; Emkay Global Financial Services Ltd.; Pantomath Capital Advisors Pvt. Ltd.',promoters:'As disclosed in RHP',revenue:'₹1,678.98 Cr (FY26)',profit:'₹79.89 Cr (FY26)',debt:'Fresh proceeds include repayment of ₹7.70 Cr borrowings',objects:'₹226.33 Cr manufacturing expansion and hybrid wind-solar project; ₹7.70 Cr repayment of borrowings; general corporate purposes.',source:'IPO Ji / RHP analysis',sourceDate:'28 Sep 2026'},
   {name:'Orient Cables (India) Limited',slug:'orient-cables-ipo',type:'Mainboard',symbol:'ORIENTCABLE',status:'Open',open:'25 Sep 2026',close:'29 Sep 2026',allotment:'30 Sep 2026',refund:'01 Oct 2026',credit:'01 Oct 2026',listing:'05 Oct 2026',band:'₹258–₹272',faceValue:'₹1',lot:55,min:14960,issue:'₹552 Cr',fresh:'₹320 Cr',ofs:'₹232 Cr',freshShares:'1,17,64,705',ofsShares:'85,29,412',subscription:'8.77x',qib:'0.06x',nii:'18.31x',retail:'9.65x',gmp:78,gmpUpdated:'28 Sep 2026 17:00 IST',gmpSource:'IPO Ji',sector:'Cables / electricals',exchange:'BSE, NSE',registrar:'KFin Technologies Ltd.',leadManagers:'IIFL Capital Services Ltd.; JM Financial Ltd.',promoters:'Vipul Nagpal; Garima Nagpal; Vardaan Nagpal; Vipul Family Trust; Garima Family Trust',revenue:'₹1,678.98 Cr (FY26)',profit:'₹79.88 Cr (FY26)',debt:'See RHP balance sheet',objects:'Fresh issue objects and general corporate purposes as detailed in the RHP.',source:'IPO Ji / NSE-BSE compiled data',sourceDate:'28 Sep 2026 17:00 IST'},
   {name:'Runwal Enterprises Limited',slug:'runwal-enterprises-ipo',type:'Mainboard',symbol:'RUNWALENTR',status:'Open',open:'25 Sep 2026',close:'29 Sep 2026',allotment:'30 Sep 2026',refund:'01 Oct 2026',credit:'01 Oct 2026',listing:'05 Oct 2026',band:'₹290–₹305',faceValue:'₹2',lot:49,min:14945,issue:'₹500 Cr',fresh:'₹500 Cr',ofs:'₹0',subscription:'0.75x',qib:'1.11x',nii:'0.99x',retail:'0.44x',gmp:14,gmpUpdated:'28 Sep 2026 21:00 IST',gmpSource:'IPO Guru / IPO Ji',sector:'Real estate',exchange:'BSE, NSE',registrar:'MUFG Intime India Pvt. Ltd.',leadManagers:'As disclosed in RHP',promoters:'Runwal group / as disclosed in RHP',revenue:'See RHP / latest financial statements',profit:'See RHP / latest financial statements',debt:'Leverage is a key RHP disclosure',objects:'Fresh issue proceeds as specified in the RHP.',source:'IPO Ji / IPO Guru',sourceDate:'28 Sep 2026'},
   {name:'AceVector Limited (Snapdeal)',slug:'acevector-ipo',type:'Mainboard',symbol:'ACEVECTOR',status:'Open',open:'25 Sep 2026',close:'29 Sep 2026',allotment:'30 Sep 2026',refund:'01 Oct 2026',credit:'01 Oct 2026',listing:'05 Oct 2026',band:'₹30–₹32',faceValue:'₹1',lot:468,min:14976,issue:'₹420 Cr',fresh:'₹287 Cr',ofs:'₹133 Cr',subscription:'1.19x',qib:'1.05x',nii:'1.31x',retail:'1.43x',gmp:1,gmpUpdated:'28 Sep 2026 17:00 IST',gmpSource:'IPO Ji',sector:'Digital commerce',exchange:'BSE, NSE',registrar:'MUFG Intime India Pvt. Ltd.',leadManagers:'IIFL Capital Services Ltd.; CLSA India Pvt. Ltd.; Systematix Corporate Services Ltd.',promoters:'As disclosed in RHP',revenue:'See RHP',profit:'See RHP',debt:'See RHP',objects:'Fresh issue objects include uses detailed in the RHP; OFS proceeds go to selling shareholders.',source:'IPO Ji / exchange data',sourceDate:'28 Sep 2026 17:06 IST'},
   {name:'SRIT India Limited',slug:'srit-india-ipo',type:'Mainboard',symbol:'SRIT',status:'Open',open:'28 Sep 2026',close:'30 Sep 2026',allotment:'01 Oct 2026',refund:'05 Oct 2026',credit:'05 Oct 2026',listing:'06 Oct 2026',band:'₹123–₹130',faceValue:'₹5',lot:115,min:14950,issue:'₹218.40 Cr',fresh:'₹218.40 Cr',ofs:'₹0',subscription:'0.99x',qib:'0.00x',nii:'0.89x',retail:'1.60x',gmp:33,gmpUpdated:'28 Sep 2026 09:53 IST',gmpSource:'InvestKraft / IPOWatch',sector:'IT / digital solutions',exchange:'BSE, NSE',registrar:'As disclosed in RHP',leadManagers:'As disclosed in RHP',promoters:'As disclosed in RHP',revenue:'See RHP',profit:'See RHP',debt:'See RHP',objects:'Fresh issue; company-specific uses are detailed in the RHP.',source:'InvestKraft / exchange data',sourceDate:'28 Sep 2026 16:14 IST'},
   {name:"Shah Investor's Home Limited",slug:'shah-investors-home-ipo',type:'Mainboard',symbol:'SIHL',status:'Open',open:'28 Sep 2026',close:'30 Sep 2026',allotment:'01 Oct 2026',refund:'05 Oct 2026',credit:'05 Oct 2026',listing:'06 Oct 2026',band:'₹159–₹167',faceValue:'₹10',lot:85,min:14195,issue:'₹90.17 Cr',fresh:'₹90.17 Cr',ofs:'₹0',subscription:'0.31x',qib:'0.50x',nii:'0.25x',retail:'0.23x',gmp:9,gmpUpdated:'27 Sep 2026',gmpSource:'IPOMarkets',sector:'Stock broking / financial services',exchange:'BSE, NSE',registrar:'MUFG Intime India Pvt. Ltd.',leadManagers:'Beeline Capital Advisors Pvt. Ltd.',promoters:'Upendra Trikamlal Shah; Purnima Upendra Shah; Tanmay Upendra Shah; Trupti Utpal Shah',revenue:'₹71.48 Cr (FY26)',profit:'₹13.20 Cr (FY26)',debt:'Borrowings ₹18.47 Cr (FY26)',objects:'₹60 Cr working capital; general corporate purposes.',source:'SAMCO / IPOMarkets / exchange data',sourceDate:'28 Sep 2026'}
  ],
  sme:[
   {name:'Green Asia Impex Limited',slug:'green-asia-impex-ipo',type:'SME',symbol:'GREENASIA',status:'Closed',open:'24 Sep 2026',close:'28 Sep 2026',allotment:'29 Sep 2026',refund:'30 Sep 2026',credit:'30 Sep 2026',listing:'01 Oct 2026',band:'₹85–₹90',faceValue:'₹10',lot:1600,min:288000,issue:'₹60.10 Cr',fresh:'₹53.10 Cr',ofs:'₹7.00 Cr',subscription:'0.48x',qib:'1.17x',nii:'0.17x',retail:'0.19x',gmp:0,gmpUpdated:'28 Sep 2026',gmpSource:'DostiIPO / IPO Ji',sector:'Agro / food products',exchange:'NSE SME',registrar:'Bigshare Services Pvt. Ltd.',leadManagers:'Indorient Financial Services Ltd.',promoters:'As disclosed in RHP',revenue:'₹339.7 Cr (FY25)',profit:'₹10.1 Cr (FY25)',debt:'See latest RHP',objects:'Fresh issue and OFS objects as detailed in RHP.',source:'IPO Ji / HDFC Sky',sourceDate:'28 Sep 2026 17:57 IST'},
   {name:'Roopa Screen Limited',slug:'roopa-screen-ipo',type:'SME',symbol:'ROOPASCREEN',status:'Closed',open:'24 Sep 2026',close:'28 Sep 2026',allotment:'29 Sep 2026',refund:'30 Sep 2026',credit:'30 Sep 2026',listing:'01 Oct 2026',band:'₹60–₹64',faceValue:'₹10',lot:2000,min:128000,issue:'₹19.20 Cr',fresh:'₹19.20 Cr',ofs:'₹0',subscription:'387.61x',qib:'111.63x',nii:'422.44x',retail:'529.82x',gmp:14,gmpUpdated:'28 Sep 2026',gmpSource:'GMP Updates',sector:'Industrial screens',exchange:'BSE SME',registrar:'Bigshare Services Pvt. Ltd.',leadManagers:'As disclosed in RHP',promoters:'As disclosed in RHP',revenue:'₹51.32 Cr (FY26)',profit:'₹6.48 Cr (FY26)',debt:'See RHP',objects:'Entirely fresh issue; see RHP for use of proceeds.',source:'Moneycontrol / HDFC Sky / BSE data',sourceDate:'28 Sep 2026 18:47 IST'},
   {name:'Peshwa Wheat Limited',slug:'peshwa-wheat-ipo',type:'SME',symbol:'PESHWA',status:'Closed',open:'24 Sep 2026',close:'28 Sep 2026',allotment:'29 Sep 2026',refund:'30 Sep 2026',credit:'30 Sep 2026',listing:'01 Oct 2026',band:'₹95–₹101',faceValue:'₹10',lot:2400,min:242400,issue:'₹53.52 Cr',fresh:'₹53.52 Cr',ofs:'₹0',subscription:'2.83x',qib:'177.12x',nii:'0.47x',retail:'1.72x',gmp:null,gmpUpdated:null,gmpSource:null,sector:'Food processing',exchange:'BSE SME',registrar:'Maashitla Securities Pvt. Ltd.',leadManagers:'Finaax Capital Advisors Pvt. Ltd.',promoters:'As disclosed in RHP',revenue:'See RHP',profit:'See RHP',debt:'See RHP',objects:'Entirely fresh issue; see RHP for use of proceeds.',source:'IPO Ji / HDFC Sky',sourceDate:'28 Sep 2026 17:57 IST'},
   {name:'Dudani Retail Limited',slug:'dudani-retail-ipo',type:'SME',symbol:'DUDANI',status:'Open',open:'25 Sep 2026',close:'29 Sep 2026',allotment:'30 Sep 2026',refund:'01 Oct 2026',credit:'01 Oct 2026',listing:'06 Oct 2026',band:'₹29',faceValue:'₹10',lot:4000,min:116000,issue:'₹10.54 Cr',fresh:'See RHP',ofs:'See RHP',subscription:'0.28x',qib:'—',nii:'0.06x',retail:'0.49x',gmp:3,gmpUpdated:'28 Sep 2026',gmpSource:'IPO Market',sector:'Retail',exchange:'BSE SME',registrar:'As disclosed in RHP',leadManagers:'As disclosed in RHP',promoters:'As disclosed in RHP',revenue:'See RHP',profit:'See RHP',debt:'See RHP',objects:'See RHP.',source:'IPO Ji / IPO Market',sourceDate:'28 Sep 2026 17:00 IST'},
   {name:'Himalayan Solar Limited',slug:'himalayan-solar-ipo',type:'SME',symbol:'HIMALAYAN',status:'Open',open:'25 Sep 2026',close:'29 Sep 2026',allotment:'30 Sep 2026',refund:'01 Oct 2026',credit:'01 Oct 2026',listing:'06 Oct 2026',band:'₹98–₹103',faceValue:'₹10',lot:1200,min:123600,issue:'₹68.03 Cr',fresh:'See RHP',ofs:'See RHP',subscription:'0.77x',qib:'1.58x',nii:'0.44x',retail:'0.84x',gmp:0,gmpUpdated:'28 Sep 2026',gmpSource:'IPO Ji',sector:'Renewable energy',exchange:'NSE SME',registrar:'As disclosed in RHP',leadManagers:'As disclosed in RHP',promoters:'As disclosed in RHP',revenue:'See RHP',profit:'See RHP',debt:'See RHP',objects:'See RHP.',source:'IPO Ji',sourceDate:'28 Sep 2026 17:54 IST'},
   {name:'Sai Urja Indo Ventures Limited',slug:'sai-urja-indo-ventures-ipo',type:'SME',symbol:'SAIURJA',status:'Open',open:'25 Sep 2026',close:'29 Sep 2026',allotment:'30 Sep 2026',refund:'01 Oct 2026',credit:'01 Oct 2026',listing:'06 Oct 2026',band:'₹107–₹113',faceValue:'₹10',lot:1200,min:135600,issue:'₹24.95 Cr',fresh:'See RHP',ofs:'See RHP',subscription:'0.23x',qib:'0.00x',nii:'0.08x',retail:'0.43x',gmp:0,gmpUpdated:'28 Sep 2026',gmpSource:'IPO Ji',sector:'Engineering / energy',exchange:'BSE SME',registrar:'As disclosed in RHP',leadManagers:'As disclosed in RHP',promoters:'As disclosed in RHP',revenue:'See RHP',profit:'See RHP',debt:'See RHP',objects:'See RHP.',source:'IPO Ji',sourceDate:'28 Sep 2026 17:00 IST'},
   {name:'Shivchem Agro Limited',slug:'shivchem-agro-ipo',type:'SME',symbol:'SHIVCHEM',status:'Open',open:'28 Sep 2026',close:'30 Sep 2026',allotment:'01 Oct 2026',refund:'05 Oct 2026',credit:'05 Oct 2026',listing:'06 Oct 2026',band:'₹59–₹62',faceValue:'₹5',lot:4000,min:248000,issue:'₹14.01 Cr',fresh:'₹14.01 Cr',ofs:'₹0',subscription:'0.11x',qib:'0.00x',nii:'0.14x',retail:'0.10x',gmp:6,gmpUpdated:'28 Sep 2026 16:07 IST',gmpSource:'IPOWatch',sector:'Agrochemicals',exchange:'BSE SME',registrar:'As disclosed in RHP',leadManagers:'As disclosed in RHP',promoters:'As disclosed in RHP',revenue:'See RHP',profit:'See RHP',debt:'See RHP',objects:'Entirely fresh issue; see RHP.',source:'IPOWatch / IPO Ji',sourceDate:'28 Sep 2026'}
  ]
 },
 news:[
  {title:'Nifty 50 closed at 22,780.25, down 1.56%, while Sensex ended at 72,771.72.',tag:'MARKET CLOSE',source:'Upstox / market feeds',age:'28 Sep'},
  {title:'FII cash-market net selling was ₹5,353.22 Cr while DII net buying was ₹5,189.02 Cr.',tag:'FII / DII',source:'Trendlyne / NSE aggregate',age:'28 Sep'},
  {title:'Moneyview closed with 101.87x overall subscription; QIB was 230.54x and retail 20.41x.',tag:'IPO',source:'IPO Ji / exchange data',age:'28 Sep'},
  {title:'Orient Cables reached 8.77x subscription with QIB 0.06x, NII 18.31x and retail 9.65x.',tag:'IPO',source:'IPO Ji / exchange data',age:'28 Sep'},
  {title:'Roopa Screen closed with 387.61x overall subscription in the latest compiled exchange snapshot.',tag:'SME IPO',source:'IPO Ji / BSE data',age:'28 Sep'}
 ]
};

function clone(x){return JSON.parse(JSON.stringify(x))}
function money(n,dec=2){if(n===null||n===undefined||n===''||Number.isNaN(Number(n)))return '—';return new Intl.NumberFormat('en-IN',{maximumFractionDigits:dec,minimumFractionDigits:dec}).format(Number(n))}
function pct(n){return n===null||n===undefined||Number.isNaN(Number(n))?'—':`${Number(n)>=0?'+':''}${Number(n).toFixed(2)}%`}
function parseNum(v){const n=Number(v);return Number.isFinite(n)?n:0}
function bandHigh(band){const m=String(band||'').match(/([\d,.]+)\s*[–-]\s*([\d,.]+)/);return m?parseNum(m[2].replace(/,/g,'')):parseNum(String(band).replace(/[^\d.]/g,''))}
function slugify(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}

function useData(){
 const [data,setData]=useState(()=>{try{const cached=JSON.parse(localStorage.getItem('bb-shared-data'));return cached?.data?cached.data:clone(SEED)}catch{return clone(SEED)}});
 const [last,setLast]=useState(()=>{try{return localStorage.getItem('bb-shared-last')||SEED.updatedAt}catch{return SEED.updatedAt}});
 const [loading,setLoading]=useState(false),[msg,setMsg]=useState('');
 const refresh=async(manual=false)=>{
  setLoading(true);setMsg('');
  try{
   const r=await fetch(`/data/latest.json?t=${Date.now()}`,{cache:'no-store'});
   if(!r.ok)throw new Error(`Shared data feed returned HTTP ${r.status}.`);
   const next=await r.json();
   if(!next || !next.market)throw new Error('Shared data feed is invalid.');
   setData(next);
   setLast(next.updatedAt||new Date().toISOString());
   localStorage.setItem('bb-shared-data',JSON.stringify({data:next}));
   localStorage.setItem('bb-shared-last',next.updatedAt||new Date().toISOString());
  }catch(e){setMsg(manual?e.message:'Shared data feed unavailable; showing the last successful data.')}finally{setLoading(false)}
 };
 useEffect(()=>{refresh(false);const timer=setInterval(()=>refresh(false),TWO_HOURS);const vis=()=>{if(document.visibilityState==='visible')refresh(false)};document.addEventListener('visibilitychange',vis);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',vis)}},[]);
 return {data,last,loading,msg,refresh}
}
function Header({state,onNav}){return <><div className="top"><div className="brand" onClick={()=>onNav('/')}>BAZAAR<span>BRIEF</span></div><div className="tag">INDIA'S DAILY MARKET BRIEF</div><button onClick={()=>state.refresh(true)} disabled={state.loading}>{state.loading?'Updating…':'↻ Refresh data'}</button></div><div className="nav"><a onClick={()=>onNav('/')}>Markets</a><a onClick={()=>onNav('/ipo')}>IPO</a><a onClick={()=>onNav('/ipo-calendar')}>IPO Calendar</a><a onClick={()=>onNav('/gmp')}>GMP</a><a onClick={()=>onNav('/ipo-allotment-status')}>Allotment</a><a onClick={()=>onNav('/tools')}>Financial Tools</a></div><div className="status">● {state.data.source} · Updated {new Date(state.last).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})} · Refresh target: every 2 hours while open</div></>}
function Section({title,sub,children}){return <section><div className="sectionHead"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div></div>{children}</section>}
function IndexCards({items}){return <div className="indexGrid">{items.map(x=><div className="index" key={x.name}><small>{x.name}</small><strong>{money(x.value)}</strong><span className={x.pct===null?'':x.pct>=0?'up':'down'}>{x.change===null?'Quote available':' '+(x.change>=0?'+':'')+money(x.change)+' · '+pct(x.pct)}</span>{x.note&&<em>{x.note}</em>}</div>)}</div>}
function Home({data,navigate}){const m=data.market;const gain=[...m.stocks].sort((a,b)=>b.pct-a.pct).slice(0,4),lose=[...m.stocks].sort((a,b)=>a.pct-b.pct).slice(0,4);return <main>
 <div className="hero"><div><div className="eyebrow">MARKET + IPO + TOOLS</div><h1>Your daily market brief.</h1><p>Indian markets, GIFT Nifty, IPOs, global cues and practical financial tools — in one place.</p></div><div className="heroCard"><b>Data as of</b><strong>{DATA_AS_OF}</strong><span>GIFT Nifty is an overnight/futures indicator. It is not the NIFTY 50 spot index.</span></div></div>
 <Section title="Indian Market" sub={`Latest shared market dataset · ${new Date(data.updatedAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}`}><IndexCards items={m.indices}/></Section>
 <Section title="5 things moving the market" sub="Source-dated quick read"><div className="newsGrid">{data.news.map((n,i)=><article className="news" key={i}><b>{n.tag}</b><h3>{n.title}</h3><small>{n.source} · {n.age}</small></article>)}</div></Section>
 <Section title="Top movers" sub={`Latest shared market dataset · ${new Date(data.updatedAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}`}><div className="two"><div className="panel"><h3>Top Gainers</h3>{gain.map(x=><Row x={x} key={x.symbol}/>)}</div><div className="panel"><h3>Top Losers</h3>{lose.map(x=><Row x={x} key={x.symbol}/>)}</div></div></Section>
 <Section title="FII / DII Activity" sub={`Cash market · ${data.fiiDii.date}`}><div className="two"><div className="flow"><small>FII / FPI NET</small><strong className="down">₹{money(Math.abs(data.fiiDii.fii))} Cr</strong><span>Net selling</span></div><div className="flow"><small>DII NET</small><strong className="up">+₹{money(data.fiiDii.dii)} Cr</strong><span>Net buying</span></div></div></Section>
 <Section title="Global Markets & Commodities"><div className="commodityGrid">{m.global.concat(m.commodities).map(x=><div className="commodity" key={x.name}><small>{x.name}</small><strong>{x.unit||''}{money(x.value)}</strong><span className={x.pct>=0?'up':'down'}>{pct(x.pct)}</span></div>)}</div></Section>
 <Section title="IPO" sub="Mainboard and SME are separate sections"><div className="ipoSplit"><div><div className="subHead"><h3>Mainboard IPOs</h3><button onClick={()=>navigate('/ipo/mainboard')}>View all →</button></div><div className="ipoGrid">{data.ipo.mainboard.filter(x=>x.status==='Open').slice(0,3).map(x=><IPOCard x={x} key={x.slug} navigate={navigate}/>)}</div></div><div><div className="subHead"><h3>SME IPOs</h3><button onClick={()=>navigate('/ipo/sme')}>View all →</button></div><div className="ipoGrid">{data.ipo.sme.filter(x=>x.status==='Open').slice(0,3).map(x=><IPOCard x={x} key={x.slug} navigate={navigate}/>)}</div></div></div></Section>
 <Section title="Financial Tools" sub="Instant browser calculators"><div className="tools">{Object.entries(TOOL_DEFS).map(([k,t])=><div key={k} onClick={()=>navigate('/tools/'+k)}>{t.title}<span>→</span></div>)}</div></Section>
 </main>}
function Row({x}){return <div className="row"><div><b>{x.symbol}</b><small>{x.name}</small></div><strong>₹{money(x.price)}</strong><span className={x.pct>=0?'up':'down'}>{pct(x.pct)}</span></div>}
function IPOCard({x,navigate}){const g=x.gmp===null||x.gmp===undefined?'—':`₹${money(x.gmp,0)}`;const listing=x.gmp!==null&&x.gmp!==undefined?`₹${money(bandHigh(x.band)+x.gmp)}`:'—';return <article className="ipoCard"><div className="ipoTop"><span>{x.type}</span><b>{x.status}</b></div><h3>{x.name}</h3><p>{x.band} · Lot {money(x.lot,0)}</p><div className="ipoMeta"><div><small>Issue</small><b>{x.issue}</b></div><div><small>Close</small><b>{x.close}</b></div><div><small>GMP*</small><b>{g}</b></div></div><div className="ipoMeta"><div><small>Subscription</small><b>{x.subscription}</b></div><div><small>Min. invest.</small><b>₹{money(x.min,0)}</b></div><div><small>GMP est.</small><b>{listing}</b></div></div><button onClick={()=>navigate('/ipo/'+x.type.toLowerCase()+'/'+x.slug)}>View IPO →</button></article>}
function allIPOs(data){return [...data.ipo.mainboard,...data.ipo.sme]}
function IPOPage({data,kind,slug,navigate}){const list=kind==='mainboard'?data.ipo.mainboard:kind==='sme'?data.ipo.sme:allIPOs(data);if(slug){const x=allIPOs(data).find(i=>i.slug===slug)||list[0];return <main><div className="pageTitle"><span>{x.type.toUpperCase()} IPO · {x.status}</span><h1>{x.name}</h1><p>All figures are source-dated. GMP is unofficial and market-reported.</p></div><div className="detailGrid">{[['Status',x.status],['Price band',x.band],['Face value',x.faceValue],['IPO dates',`${x.open} → ${x.close}`],['Lot size',x.lot+' shares'],['Minimum investment',`₹${money(x.min,0)}`],['Issue size',x.issue],['Fresh issue',x.fresh],['OFS',x.ofs],['Subscription',x.subscription],['QIB',x.qib],['NII / HNI',x.nii],['Retail / Individual',x.retail],['GMP*',x.gmp===null?'Not reported':`₹${money(x.gmp,0)}`],['GMP updated',x.gmpUpdated||'—'],['Indicative listing price*',x.gmp===null?'—':`₹${money(bandHigh(x.band)+x.gmp)}`],['Allotment',x.allotment],['Refund',x.refund],['Demat credit',x.credit],['Listing',x.listing],['Exchange',x.exchange],['Registrar',x.registrar],['Lead manager(s)',x.leadManagers]].map(([a,b])=><div className="detail" key={a}><small>{a}</small><strong>{b||'—'}</strong></div>)}</div><div className="two"><div className="panel"><h2>Financial results</h2><RowText a="Revenue" b={x.revenue}/><RowText a="Profit / PAT" b={x.profit}/><RowText a="Debt / borrowings" b={x.debt}/><RowText a="Promoters" b={x.promoters}/></div><div className="panel"><h2>Issue purpose</h2><p className="longText">{x.objects}</p><RowText a="Sector" b={x.sector}/><RowText a="Source" b={x.source}/><RowText a="Source date" b={x.sourceDate}/></div></div><div className="panel"><h2>GMP disclosure</h2><p className="longText">GMP is an unofficial grey-market quote. It is not exchange-published, may vary between trackers and can change rapidly. The indicative listing price above is only the arithmetic of upper price band + reported GMP; it is not a forecast or guarantee.</p></div><button className="back" onClick={()=>navigate(kind?`/ipo/${kind}`:'/ipo')}>← Back to {kind||'all IPOs'}</button></main>}
 return <main><div className="pageTitle"><span>{kind?kind.toUpperCase()+' IPO':'IPO'}</span><h1>{kind==='mainboard'?'Mainboard IPOs':kind==='sme'?'SME IPOs':'Indian IPOs'}</h1><p>{kind==='mainboard'?'Mainboard issues with price, lot, subscription, GMP and key company fields.':kind==='sme'?'SME issues with higher lot/application requirements shown separately.':'Mainboard and SME IPOs, separated for easier discovery.'}</p></div><div className="ipoTabs"><button onClick={()=>navigate('/ipo/mainboard')}>Mainboard</button><button onClick={()=>navigate('/ipo/sme')}>SME</button><button onClick={()=>navigate('/ipo')}>All</button></div><div className="ipoGrid">{list.map(x=><IPOCard x={x} key={x.slug} navigate={navigate}/>)}</div></main>}
function RowText({a,b}){return <div className="rowText"><span>{a}</span><b>{b}</b></div>}
function Calendar({data,navigate}){const rows=allIPOs(data);return <main><div className="pageTitle"><span>CALENDAR</span><h1>IPO Calendar</h1><p>Open, close, allotment, refund, credit and listing dates.</p></div><div className="ipoTabs"><button onClick={()=>navigate('/ipo/mainboard')}>Mainboard</button><button onClick={()=>navigate('/ipo/sme')}>SME</button></div><div className="tableWrap"><table><thead><tr><th>IPO</th><th>Type</th><th>Status</th><th>Open</th><th>Close</th><th>Allotment</th><th>Listing</th><th>Price</th><th>Lot</th><th>GMP</th></tr></thead><tbody>{rows.map(x=><tr key={x.slug}><td><b>{x.name}</b><small>{x.symbol}</small></td><td>{x.type}</td><td>{x.status}</td><td>{x.open}</td><td>{x.close}</td><td>{x.allotment}</td><td>{x.listing}</td><td>{x.band}</td><td>{x.lot}</td><td>{x.gmp===null?'—':'₹'+money(x.gmp,0)}</td></tr>)}</tbody></table></div></main>}
function GMP({data}){const rows=allIPOs(data);return <main><div className="pageTitle"><span>UNOFFICIAL · SOURCE DATED</span><h1>IPO GMP Today</h1><p>Latest reported grey-market premium available in the audited snapshot. Different trackers can quote different GMPs.</p></div><div className="tableWrap"><table><thead><tr><th>IPO</th><th>Type</th><th>Upper band</th><th>GMP</th><th>Indicative price*</th><th>GMP %</th><th>Subscription</th><th>GMP as of</th></tr></thead><tbody>{rows.map(x=>{const hi=bandHigh(x.band);const g=x.gmp;return <tr key={x.slug}><td><b>{x.name}</b></td><td>{x.type}</td><td>₹{money(hi,2)}</td><td className={g>0?'up':''}>{g===null?'Not reported':'₹'+money(g,0)}</td><td>{g===null?'—':'₹'+money(hi+g,2)}</td><td>{g===null?'—':pct(g/hi*100)}</td><td>{x.subscription}</td><td>{x.gmpUpdated||'—'}</td></tr>})}</tbody></table></div></main>}
function Allotment({data}){return <main><div className="pageTitle"><span>ALLOTMENT</span><h1>IPO Allotment Status</h1><p>Expected basis-of-allotment dates and official verification route. Dates can change.</p></div><div className="ipoGrid">{allIPOs(data).map(x=><div className="panel" key={x.slug}><h2>{x.name}</h2><RowText a="Status" b={x.status}/><RowText a="Allotment" b={x.allotment}/><RowText a="Refund" b={x.refund}/><RowText a="Demat credit" b={x.credit}/><RowText a="Listing" b={x.listing}/><a className="external" href="https://www.nseindia.com/check-trades-bids-verify-ipo-bids" target="_blank" rel="noreferrer">Official NSE IPO bid/allotment check ↗</a></div>)}</div></main>}

const TOOL_DEFS={
 sip:{title:'SIP Calculator',fields:[['monthly','Monthly investment (₹)',5000],['rate','Expected annual return (%)',12],['years','Investment period (years)',10]],calc:v=>{const p=Math.max(0,parseNum(v.monthly)),r=parseNum(v.rate)/1200,n=Math.max(0,parseNum(v.years))*12,fv=r? p*((Math.pow(1+r,n)-1)/r)*(1+r):p*n,invested=p*n;return [['Invested',`₹${money(invested,0)}`],['Estimated value',`₹${money(fv,0)}`],['Estimated gain',`₹${money(fv-invested,0)}`]]}},
 cagr:{title:'CAGR Calculator',fields:[['initial','Initial value (₹)',100000],['final','Final value (₹)',250000],['years','Years',5]],calc:v=>{const i=parseNum(v.initial),f=parseNum(v.final),y=parseNum(v.years);if(i<=0||f<0||y<=0)return [['CAGR','Enter positive values']];return [['CAGR',`${((Math.pow(f/i,1/y)-1)*100).toFixed(2)}%`]]}},
 average:{title:'Stock Average Calculator',fields:[['qty1','First quantity',100],['price1','First buy price (₹)',100],['qty2','Second quantity',100],['price2','Second buy price (₹)',80]],calc:v=>{const q1=Math.max(0,parseNum(v.qty1)),q2=Math.max(0,parseNum(v.qty2)),cost=q1*parseNum(v.price1)+q2*parseNum(v.price2),qty=q1+q2;return [['Total quantity',money(qty,0)],['Average price',qty?`₹${money(cost/qty)}`:'—'],['Total cost',`₹${money(cost,0)}`]]}},
 dividend:{title:'Dividend Calculator',fields:[['shares','Shares owned',100],['dividend','Dividend per share (₹)',10],['tax','Tax / withholding (%)',0]],calc:v=>{const gross=Math.max(0,parseNum(v.shares))*Math.max(0,parseNum(v.dividend)),tax=Math.max(0,parseNum(v.tax))*gross/100;return [['Gross dividend',`₹${money(gross,2)}`],['Tax',`₹${money(tax,2)}`],['Net dividend',`₹${money(gross-tax,2)}`]]}},
 pe:{title:'P/E Calculator',fields:[['price','Share price (₹)',500],['eps','EPS (₹)',25]],calc:v=>{const e=parseNum(v.eps);return [['P/E ratio',e>0?`${(parseNum(v.price)/e).toFixed(2)}x`:'—']]}},
 eps:{title:'EPS Calculator',fields:[['profit','Net profit (₹)',10000000],['shares','Weighted average shares',1000000]],calc:v=>{const s=parseNum(v.shares);return [['EPS',s>0?`₹${money(parseNum(v.profit)/s,2)}`:'—']]}},
 roe:{title:'ROE Calculator',fields:[['profit','Net profit (₹)',10000000],['equity','Average shareholders equity (₹)',50000000]],calc:v=>{const e=parseNum(v.equity);return [['ROE',e>0?`${(parseNum(v.profit)/e*100).toFixed(2)}%`:'—']]}},
 roce:{title:'ROCE Calculator',fields:[['ebit','EBIT (₹)',12000000],['capital','Capital employed (₹)',80000000]],calc:v=>{const c=parseNum(v.capital);return [['ROCE',c>0?`${(parseNum(v.ebit)/c*100).toFixed(2)}%`:'—']]}},
 marketcap:{title:'Market Cap Calculator',fields:[['price','Share price (₹)',500],['shares','Shares outstanding',10000000]],calc:v=>{const cap=parseNum(v.price)*parseNum(v.shares);return [['Market cap (₹)',`₹${money(cap,0)}`],['Market cap (₹ Cr)',`₹${money(cap/10000000,2)} Cr`]]}},
 profitgrowth:{title:'Profit Growth Calculator',fields:[['old','Previous profit (₹)',10000000],['new','Current profit (₹)',13000000]],calc:v=>{const o=parseNum(v.old);return [['Profit growth',o!==0?`${((parseNum(v.new)-o)/Math.abs(o)*100).toFixed(2)}%`:'—']]}},
 ipoinvestment:{title:'IPO Investment Calculator',fields:[['lot','Shares per lot',100],['price','IPO price per share (₹)',500],['lots','Number of lots',1]],calc:v=>{const lot=Math.max(0,parseNum(v.lot)),lots=Math.max(0,parseNum(v.lots)),inv=lot*parseNum(v.price)*lots;return [['Total shares',money(lot*lots,0)],['Investment',`₹${money(inv,0)}`]]}},
 ipoprofit:{title:'IPO Profit Calculator',fields:[['shares','Shares allotted',100],['buy','IPO price (₹)',500],['sell','Listing / sale price (₹)',650],['costs','Taxes + charges (₹)',0]],calc:v=>{const shares=Math.max(0,parseNum(v.shares)),buy=parseNum(v.buy),sell=parseNum(v.sell),costs=Math.max(0,parseNum(v.costs)),gross=(sell-buy)*shares,net=gross-costs;return [['Gross profit',`₹${money(gross,0)}`],['Costs',`₹${money(costs,0)}`],['Net profit',`₹${money(net,0)}`],['Return',buy>0?`${((sell-buy)/buy*100).toFixed(2)}%`:'—']]}},
 ipogmp:{title:'IPO GMP Calculator',fields:[['ipo','Upper price band (₹)',500],['gmp','GMP (₹)',80]],calc:v=>{const price=parseNum(v.ipo),g=parseNum(v.gmp);return [['Indicative listing price',`₹${money(price+g,2)}`],['Indicative premium',price?`${(g/price*100).toFixed(2)}%`:'—']]}},
 allotment:{title:'IPO Allotment Estimate',fields:[['applications','Applications received',100000],['lots','Lots available',5000]],calc:v=>{const a=Math.max(0,parseNum(v.applications)),l=Math.max(0,parseNum(v.lots));const p=a?Math.min(100,l/a*100):0;return [['Simple mathematical estimate',`${p.toFixed(2)}%`],['Disclaimer','Not a prediction; actual allotment follows category rules and registrar lottery/process.']]}},
 usd:{title:'USD / INR Converter',fields:[['usd','USD amount',100],['rate','USD/INR rate',96]],calc:v=>[['INR value',`₹${money(parseNum(v.usd)*parseNum(v.rate),2)}`]]},
 emi:{title:'EMI Calculator',fields:[['principal','Loan amount (₹)',1000000],['rate','Annual interest (%)',8.5],['years','Tenure (years)',10]],calc:v=>{const p=parseNum(v.principal),r=parseNum(v.rate)/1200,n=parseNum(v.years)*12;const emi=r? p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):(n?p/n:0);return [['Monthly EMI',`₹${money(emi,0)}`],['Total payment',`₹${money(emi*n,0)}`],['Total interest',`₹${money(emi*n-p,0)}`]]}},
 lumpsum:{title:'Lumpsum Calculator',fields:[['principal','Initial investment (₹)',100000],['rate','Expected annual return (%)',12],['years','Years',10]],calc:v=>{const p=parseNum(v.principal),r=parseNum(v.rate)/100,y=parseNum(v.years),fv=p*Math.pow(1+r,y);return [['Invested',`₹${money(p,0)}`],['Future value',`₹${money(fv,0)}`],['Gain',`₹${money(fv-p,0)}`]]}}
};
function Calculator({def}){const initial=Object.fromEntries(def.fields.map(([k,,v])=>[k,v]));const [v,setV]=useState(initial);useEffect(()=>setV(initial),[def.title]);const result=useMemo(()=>def.calc(v),[def,v]);return <div className="calculator"><h2>{def.title}</h2><div className="fieldGrid">{def.fields.map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="any" value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})}/></label>)}</div><div className="results">{result.map(([a,b])=><div className="resultRow" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></div>}
function Tools({tool}){const [active,setActive]=useState(tool&&TOOL_DEFS[tool]?tool:'sip');return <main><div className="pageTitle"><span>TOOLS</span><h1>Financial Tools</h1><p>Formula-based browser calculators with validation and instant results.</p></div><div className="toolSelector">{Object.entries(TOOL_DEFS).map(([k,d])=><button className={active===k?'active':''} key={k} onClick={()=>setActive(k)}>{d.title}</button>)}</div><Calculator def={TOOL_DEFS[active]}/><div className="toolNote"><b>Important:</b> calculators are mathematical tools, not investment advice. IPO GMP is unofficial; allotment estimation is not a prediction.</div></main>}
function Footer(){return <footer>BAZAAR BRIEF · Market data can be delayed. GIFT Nifty is a futures/pre-market indicator, not NIFTY 50 spot. GMP is unofficial / market-reported. Verify important figures against NSE/BSE, registrar pages and official IPO documents.</footer>}
function App(){const state=useData();const [path,setPath]=useState(location.pathname.replace(/\/$/,'')||'/');const nav=p=>{history.pushState({},'',p);setPath(p);window.scrollTo({top:0,behavior:'smooth'})};useEffect(()=>{const f=()=>setPath(location.pathname.replace(/\/$/,'')||'/');addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);let content;if(path==='/ipo')content=<IPOPage data={state.data} navigate={nav}/>;else if(path==='/ipo/mainboard')content=<IPOPage data={state.data} kind="mainboard" navigate={nav}/>;else if(path==='/ipo/sme')content=<IPOPage data={state.data} kind="sme" navigate={nav}/>;else if(path.startsWith('/ipo/mainboard/'))content=<IPOPage data={state.data} kind="mainboard" slug={path.split('/')[3]} navigate={nav}/>;else if(path.startsWith('/ipo/sme/'))content=<IPOPage data={state.data} kind="sme" slug={path.split('/')[3]} navigate={nav}/>;else if(path==='/ipo-calendar')content=<Calendar data={state.data} navigate={nav}/>;else if(path==='/gmp')content=<GMP data={state.data}/>;else if(path==='/ipo-allotment-status')content=<Allotment data={state.data}/>;else if(path.startsWith('/tools/'))content=<Tools tool={path.split('/')[2]}/>;else if(path==='/tools')content=<Tools/>;else content=<Home data={state.data} navigate={nav}/>;return <><Header state={state} onNav={nav}/>{state.msg&&<div className="notice">{state.msg}</div>}{content}<Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
