import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const REFRESH_MS = 60 * 1000;
function clone(x){return JSON.parse(JSON.stringify(x))}
function money(n,dec=2){if(n===null||n===undefined||n===''||Number.isNaN(Number(n)))return '—';return new Intl.NumberFormat('en-IN',{maximumFractionDigits:dec,minimumFractionDigits:dec}).format(Number(n))}
function pct(n){return n===null||n===undefined||Number.isNaN(Number(n))?'—':`${Number(n)>=0?'+':''}${Number(n).toFixed(2)}%`}
function parseNum(v){const n=Number(v);return Number.isFinite(n)?n:0}
function bandHigh(band){const m=String(band||'').match(/([\d,.]+)\s*[–-]\s*([\d,.]+)/);return m?parseNum(m[2].replace(/,/g,'')):parseNum(String(band).replace(/[^\d.]/g,''))}
function slugify(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}

function useData(){
 const [data,setData]=useState(null);
 const [last,setLast]=useState(null);
 const [loading,setLoading]=useState(true);
 const [msg,setMsg]=useState('Loading live shared API data…');
 const refresh=async(manual=false)=>{
  setLoading(true);setMsg(manual?'Refreshing shared API data…':'Loading shared API data…');
  try{
   const r=await fetch(`/data/latest.json?t=${Date.now()}`,{cache:'no-store'});
   if(!r.ok)throw new Error(`Shared API dataset returned HTTP ${r.status}.`);
   const next=await r.json();
   if(!next || next.dataPolicy?.primary!=='API-only' || !next.market || next.refresh?.status!=='ok'){
    throw new Error('Live API dataset is unavailable or not marked API-only.');
   }
   const normalized={
    ...next,
    source: next.source || 'API-only shared scheduled feed',
    market: {
      ...(next.market||{}),
      indices: Array.isArray(next.market?.indices)?next.market.indices:[],
      global: Array.isArray(next.market?.global)?next.market.global:[],
      commodities: Array.isArray(next.market?.commodities)?next.market.commodities:[],
      stocks: Array.isArray(next.market?.stocks)?next.market.stocks:[]
    },
    fiiDii: next.fiiDii || {},
    ipo: {
      ...(next.ipo||{}),
      mainboard: Array.isArray(next.ipo?.mainboard)?next.ipo.mainboard:[],
      sme: Array.isArray(next.ipo?.sme)?next.ipo.sme:[]
    },
    news: Array.isArray(next.news)?next.news:[]
   };
   setData(normalized);setLast(normalized.updatedAt||null);setMsg('');
  }catch(e){
   setData(null);setLast(null);setMsg(e.message);
  }finally{setLoading(false)}
 };
 useEffect(()=>{
  refresh(false);
  const timer=setInterval(()=>refresh(false),REFRESH_MS);
  const vis=()=>{if(document.visibilityState==='visible')refresh(false)};
  document.addEventListener('visibilitychange',vis);
  return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',vis)}
 },[]);
 return {data,last,loading,msg,refresh}
}
function fmtDate(value){return value?new Date(value).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—'}
function Sparkline({series=[]}){const values=series.map(x=>Number(x?.v)).filter(Number.isFinite);if(values.length<2)return null;const min=Math.min(...values),max=Math.max(...values);const d=values.map((v,i)=>`${i*(99/(values.length-1))},${18-((v-min)/(max-min||1))*14}`).join(' ');const positive=values[values.length-1]>=values[0];return <svg className={`spark ${positive?'sparkUp':'sparkDown'}`} viewBox="0 0 99 36" preserveAspectRatio="none" aria-hidden="true"><polyline points={d} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Header({state,onNav}){const [searchOpen,setSearchOpen]=useState(false);return <><header className="appHeader"><button className="brand" onClick={()=>onNav('/')} aria-label="Bazaar Brief home"><span className="brandMark">B</span><span>BAZAAR<span>BRIEF</span></span></button><div className="marketLive"><i></i><span>MARKET DATA</span><b>API feed</b></div><nav className="mainNav" aria-label="Primary navigation"><button className="active" onClick={()=>onNav('/')}>Markets</button><button onClick={()=>onNav('/ipo')}>IPOs</button><button onClick={()=>onNav('/gmp')}>GMP Tracker</button><button onClick={()=>onNav('/ipo-allotment-status')}>Allotment</button><button onClick={()=>onNav('/tools')}>Tools</button></nav><div className="headerActions"><button className="searchBtn" onClick={()=>setSearchOpen(v=>!v)}>⌘ K <span>Search</span></button><button className="refreshBtn" onClick={()=>state.refresh(true)} disabled={state.loading}>{state.loading?'Refreshing':'Refresh'}</button></div></header>{searchOpen&&<div className="searchPanel"><input autoFocus placeholder="Search IPOs, tools, markets…" onKeyDown={e=>{if(e.key==='Escape')setSearchOpen(false)}}/><span>Press Esc to close</span></div>}<div className="dataRail"><span><i className="pulseDot"></i> {state.data?.source || 'Waiting for shared API feed'}</span><span>Updated {fmtDate(state.last)}</span><span>Browser checks shared feed · 60s</span></div></>}
function Section({title,sub,action,children}){return <section className="dashSection"><div className="sectionHead"><div><div className="sectionKicker">{title}</div>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
function IndexCard({x}){const positive=(x.pct??0)>=0;const finalClose=Boolean(x.finalized&&x.priceType==='official_eod_close');return <article className={`indexCard ${x.name==='GIFT NIFTY'?'featured':''}`}><div className="indexTop"><span>{x.name}</span><em>{finalClose?'FINAL CLOSE':x.name==='GIFT NIFTY'?'FUTURES':'INDEX'}</em></div><div className="indexValue">{x.value==null?'—':money(x.value,2)}</div><div className="indexBottom"><span className={positive?'gain':'loss'}>{x.value==null?'Unavailable':x.change==null?`Price · ${x.asOf?fmtDate(x.asOf):'provider time unavailable'}`:`${x.change>=0?'+':''}${money(x.change,2)} · ${pct(x.pct)}`}</span><Sparkline series={x.series}/></div><small className="indexAsOf">{finalClose?'Official exchange EOD close':(x.source||'API feed')}{x.closeDate?` · ${x.closeDate}`:''}{!x.closeDate&&x.asOf?` · ${fmtDate(x.asOf)}`:''}</small>{x.note&&<small className="indexNote">{x.note}</small>}</article>}
function IndexCards({items}){return <div className="indexBento">{items.map(x=><IndexCard key={x.name} x={x}/>)}</div>}
function Home({data,navigate}){const m=data.market;const indices=[...(m.indices||[])];if(!indices.some(x=>x.name==='GIFT NIFTY'))indices.push({name:'GIFT NIFTY',value:null,change:null,pct:null,source:'GIFT Nifty provider unavailable in latest refresh',note:'No value published because the free provider did not return a current quote.'});const ranked=[...(m.stocks||[])].filter(x=>Number.isFinite(Number(x.pct)));const gain=ranked.slice().sort((a,b)=>b.pct-a.pct).slice(0,5),lose=ranked.slice().sort((a,b)=>a.pct-b.pct).slice(0,5);const commodities=m.commodities||[];return <main className="dashboard">
 <section className="heroPanel"><div className="heroCopy"><div className="eyebrow"><span></span>BAZAARBRIEF / DAILY MARKET INTELLIGENCE</div><h1>Everything moving<br/><strong>Indian markets.</strong></h1><p>One shared market feed for Nifty 50, Sensex, GIFT Nifty, IPOs, institutional flows and global cues.</p><div className="heroMeta"><span>● Shared data cache</span><span>Last sync {fmtDate(data.updatedAt)}</span><span>Market hourly · IPO/FII-DII every 2h</span></div></div><div className="heroPulse"><div className="pulseHeader"><span>MARKET PULSE</span><b>{new Date(data.updatedAt).toLocaleDateString('en-IN',{day:'2-digit',month:'short'}).toUpperCase()}</b></div><div className="pulseValue">{Number(data.fiiDii.fii)<0?'Risk-off':Number(data.fiiDii.fii)>0?'Risk-on':'Awaiting FII/DII'}</div><p>Latest institutional flow and cross-asset signals from the shared exchange/API refresh.</p><div className="pulseStats"><div><small>FII NET</small><strong className={Number(data.fiiDii.fii)>=0?'gain':'loss'}>{data.fiiDii.fii==null?'—':`₹${money(data.fiiDii.fii,0)} Cr`}</strong></div><div><small>DII NET</small><strong className={Number(data.fiiDii.dii)>=0?'gain':'loss'}>{data.fiiDii.dii==null?'—':`₹${money(data.fiiDii.dii,0)} Cr`}</strong></div></div></div></section>
 <Section title="Indian market" sub="Cash-market close + GIFT Nifty futures indicator"><IndexCards items={indices}/></Section>
 <Section title="5 things moving the market" sub="Fast context, source-stamped"><div className="storyGrid">{data.news.slice(0,5).map((n,i)=><article className="storyCard" key={i}><div className="storyTop"><span>{n.tag}</span><small>{n.age}</small></div><h3>{n.title}</h3><footer>{n.source}<span>↗</span></footer></article>)}</div></Section>
 <Section title="Market movers" sub="Largest percentage moves in the API stock feed"><div className="splitPanel"><MoverTable title="Top gainers" rows={gain}/><MoverTable title="Top losers" rows={lose}/></div></Section>
 <Section title="Institutional flow" sub={`Cash market · ${data.fiiDii.date||'Latest available'}`}><div className="flowGrid"><div className="flowCard"><div><span>FII / FPI NET</span><b className={Number(data.fiiDii.fii)>=0?'gain':'loss'}>{data.fiiDii.fii==null?'—':`₹${money(data.fiiDii.fii,0)} Cr`}</b><small>Net selling</small></div><div className="flowIcon loss">↓</div></div><div className="flowCard"><div><span>DII NET</span><b className={Number(data.fiiDii.dii)>=0?'gain':'loss'}>{data.fiiDii.dii==null?'—':`₹${money(data.fiiDii.dii,0)} Cr`}</b><small>Net buying</small></div><div className="flowIcon gain">↑</div></div></div></Section>
 <Section title="Global + commodities" sub="All values from the shared API dataset · no static market values"><div className="assetGrid">{m.global.map(x=><AssetCard key={x.name} x={x}/>)}{commodities.map(x=><AssetCard key={x.name} x={x} commodity/>)}</div><div className="sourceNote">All displayed market values come from the shared API dataset. The browser does not call financial providers directly. If the scheduled API refresh has not completed successfully, the UI waits instead of showing unverified market values.</div></Section>
 <Section title="IPO pipeline" sub="Mainboard and SME separated"><div className="ipoDashboard"><IPOPipeline title="Mainboard" items={data.ipo.mainboard.filter(x=>['open','upcoming'].includes(String(x.status).toLowerCase())).slice(0,3)} navigate={navigate}/><IPOPipeline title="SME" items={data.ipo.sme.filter(x=>['open','upcoming'].includes(String(x.status).toLowerCase())).slice(0,3)} navigate={navigate}/></div></Section>
 <Section title="Financial tools" sub="Instant, formula-based calculators"><div className="toolTiles">{Object.entries(TOOL_DEFS).slice(0,12).map(([k,t])=><button key={k} onClick={()=>navigate('/tools/'+k)}><span>{t.title}</span><b>↗</b></button>)}</div></Section>
 </main>}
function MoverTable({title,rows}){return <div className="dataPanel"><div className="panelTitle"><h3>{title}</h3><span>{rows.length} names</span></div>{rows.map(x=><div className="moverRow" key={x.symbol}><div className="stockAvatar">{x.symbol.slice(0,2)}</div><div className="stockName"><b>{x.symbol}</b><small>{x.name}</small></div><strong>₹{money(x.price)}</strong><span className={x.pct>=0?'gain':'loss'}>{pct(x.pct)}</span></div>)}</div>}
function AssetCard({x,commodity=false}){const positive=(x.pct??0)>=0;const precious=Boolean(x.precious);if(precious){const inr=x.name==='GOLD'?x.inrPer10g:x.inrPerKg;const inrUnit=x.name==='GOLD'?'₹/10g':'₹/kg';return <article className="assetCard preciousCard"><div className="assetTop"><span>{x.name}</span><em>INDIA RATE</em></div><div className="preciousQuote"><div><small>BUY RATE</small><strong>₹{money(inr,2)}</strong><span>{inrUnit} · before GST</span></div><div><small>PER GRAM</small><strong>₹{money(x.inrPerGram,2)}</strong><span>India quote</span></div></div><div className="assetBottom"><span className={positive?'gain':'loss'}>{x.pct==null?'—':pct(x.pct)}</span><Sparkline series={x.series}/></div><small className="assetAsOf">{x.source} · {x.asOf?fmtDate(x.asOf):'provider timestamp unavailable'}</small>{x.note&&<small className="assetNote">{x.note}</small>}</article>}const display=x.name==='USD/INR'?`₹${money(x.value,2)}`:`${x.unit?.startsWith('$')?'$':''}${money(x.value, x.name==='NATURAL GAS'?4:2)}`;return <article className="assetCard"><div className="assetTop"><span>{x.name}</span><em>{commodity?(x.unit||'MARKET'):'INDEX'}</em></div><strong>{display}</strong><div className="assetBottom"><span className={positive?'gain':'loss'}>{x.pct==null?'—':pct(x.pct)}</span><Sparkline series={x.series}/></div><small className="assetAsOf">{x.source||'API feed'}{x.asOf?` · ${fmtDate(x.asOf)}`:' · provider timestamp unavailable'}</small></article>}
function IPOPipeline({title,items,navigate}){return <div className="ipoPipeline"><div className="panelTitle"><h3>{title} IPO</h3><button onClick={()=>navigate('/ipo/'+title.toLowerCase())}>View all →</button></div>{items.length?items.slice(0,4).map(x=><div className="pipelineRow" key={x.slug}><div className="ipoIdentity"><div className="ipoLogo">{x.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</div><div><b>{x.name}</b><small>{x.band !== '—' ? x.band : 'Price pending'} · Lot {x.lot?money(x.lot,0):'—'} · Closes {x.close||'—'}</small></div></div><div className="subRadar"><span>NSE issue data</span><i><em style={{width:x.status==='Open'?'70%':'35%'}}></em></i><small>{x.issueType||'Public issue'} · {x.exchange||'NSE'}</small></div><div className="gmpChip nseChip"><small>NSE</small><b>{x.status}</b><span>Verified</span></div></div>):<div className="emptyState">No open or upcoming {title} IPOs in the shared dataset.</div>}</div>}
function Row({x}){return <div className="row"><div><b>{x.symbol}</b><small>{x.name}</small></div><strong>₹{money(x.price)}</strong><span className={x.pct>=0?'gain':'loss'}>{pct(x.pct)}</span></div>}
function IPOCard({x,navigate}){return <article className="ipoCard ipoCardPremium"><div className="ipoTop"><span>{x.type} · NSE VERIFIED</span><b className={String(x.status).toLowerCase()==='open'?'openStatus':''}>{x.status}</b></div><div className="ipoBrandRow"><div className="ipoLogo large">{x.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</div><div><h3>{x.name}</h3><small>{x.symbol||'NSE issue'} · {x.issueType||'Public issue'}</small></div></div><div className="ipoHeroStats"><div><small>PRICE BAND</small><strong>{x.band}</strong></div><div><small>LOT SIZE</small><strong>{x.lot?money(x.lot,0):'—'}</strong></div><div><small>MIN. INVESTMENT</small><strong>{x.min==null?'—':`₹${money(x.min,0)}`}</strong></div></div><div className="ipoDateLine"><span>Open <b>{x.open||'—'}</b></span><span>Close <b>{x.close||'—'}</b></span><span>Issue size <b>{x.issue||'—'}</b></span></div><div className="ipoCardFoot"><span>Updated {x.sourceDate||'—'}</span><button onClick={()=>navigate('/ipo/'+x.type.toLowerCase()+'/'+x.slug)}>Explore IPO →</button></div></article>}
function IpoStat({label,value}){return <div className="ipoStat"><small>{label}</small><strong>{value||'—'}</strong></div>}
function IpoSection({title,children}){return <section className="ipoDetailSection"><div className="ipoSectionTitle"><span></span><h2>{title}</h2></div>{children}</section>}
function IpoDocument({label,url}){if(!url)return null;return <a className="ipoDoc" href={url} target="_blank" rel="noreferrer"><span>{label}</span><b>↗</b></a>}
function IPOPage({data,kind,slug,navigate}){
 const list=kind==='mainboard'?data.ipo.mainboard:kind==='sme'?data.ipo.sme:allIPOs(data);
 if(slug){
  const x=allIPOs(data).find(i=>i.slug===slug)||list[0];
  if(!x)return <main className="page"><div className="emptyState">IPO not found in the latest NSE dataset.</div></main>;
  const docs=x.details||{};
  const detailEntries=Object.entries(docs).filter(([k,v])=>v!=null&&String(v).trim()!==''&&!/link$/i.test(k));
  return <main className="page ipoDetailPage">
   <div className="ipoDetailHero"><div><div className="pageEyebrow"><span></span>NSE OFFICIAL IPO DATA · {x.type.toUpperCase()}</div><h1>{x.name}</h1><p>{x.symbol||'NSE issue'} · {x.issueType||'Public issue'} · {x.status}</p></div><div className="ipoStatusBadge">{x.status}</div></div>
   <div className="ipoHeroGrid"><IpoStat label="PRICE BAND" value={x.band}/><IpoStat label="LOT SIZE" value={x.lot?`${money(x.lot,0)} shares`:'—'}/><IpoStat label="MINIMUM INVESTMENT" value={x.min==null?'—':`₹${money(x.min,0)}`}/><IpoStat label="ISSUE SIZE" value={x.issue}/></div>
   <IpoSection title="Issue overview"><div className="ipoDetailGrid"><IpoStat label="Issue period" value={x.issuePeriod}/><IpoStat label="Face value" value={x.faceValue}/><IpoStat label="Discount" value={x.discount}/><IpoStat label="Tick size" value={x.tickSize}/><IpoStat label="Minimum order quantity" value={x.minimumOrderQuantity}/><IpoStat label="IPO market timings" value={x.marketTimings}/><IpoStat label="Exchange" value={x.exchange}/><IpoStat label="Status" value={x.status}/></div></IpoSection>
   <IpoSection title="Investor limits & categories"><div className="ipoDetailGrid"><IpoStat label="Retail maximum" value={x.retailMax}/><IpoStat label="QIB maximum" value={x.qibMax}/><IpoStat label="NII maximum" value={x.niiMax}/><IpoStat label="Categories" value={x.categories}/><IpoStat label="UPI categories" value={x.upiCategories}/><IpoStat label="Subscription" value={x.subscription==null?'Not published by NSE':`${money(x.subscription,2)}x`}/><IpoStat label="QIB subscription" value={x.qib==null?'—':`${money(x.qib,2)}x`}/><IpoStat label="Retail subscription" value={x.retail==null?'—':`${money(x.retail,2)}x`}/></div></IpoSection>
   <IpoSection title="Issue management"><div className="ipoDetailGrid"><IpoStat label="Lead manager(s)" value={x.leadManagers}/><IpoStat label="Sponsor bank" value={x.sponsorBank}/><IpoStat label="Registrar" value={x.registrar}/><IpoStat label="Registrar contact" value={x.registrarContact}/><IpoStat label="Registrar address" value={x.registrarAddress}/><IpoStat label="Fresh issue" value={x.fresh}/><IpoStat label="Offer for sale" value={x.ofs}/><IpoStat label="Issue purpose" value={x.objects}/></div></IpoSection>
   <IpoSection title="Important dates"><div className="ipoTimeline"><div><span>OPEN</span><b>{x.open||'—'}</b></div><div><span>CLOSE</span><b>{x.close||'—'}</b></div><div><span>ALLOTMENT</span><b>{x.allotment||'—'}</b></div><div><span>REFUND</span><b>{x.refund||'—'}</b></div><div><span>DEMAT CREDIT</span><b>{x.credit||'—'}</b></div><div><span>LISTING</span><b>{x.listing||'—'}</b></div></div></IpoSection>
   <IpoSection title="Official NSE documents"><div className="ipoDocs"><IpoDocument label="Red Herring Prospectus" url={docs['Red Herring Prospectus Link']||x.rhp}/><IpoDocument label="Ratios / Basis of Issue Price" url={docs['Ratios / Basis of Issue Price Link']||x.basis}/><IpoDocument label="Bidding Centers" url={docs['Bidding Centers Link']||x.biddingCenters}/><IpoDocument label="Sample Application Forms" url={docs['Sample Application Forms Link']||x.sampleForms}/><IpoDocument label="Security Parameters" url={docs['Security Parameters (Pre Anchor) Link']||x.securityParameters}/><IpoDocument label="ASBA e-form" url={x.eform}/></div></IpoSection>
   <IpoSection title="Complete NSE issue information"><div className="nseRawGrid">{detailEntries.map(([label,value])=><div className="nseRawItem" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></IpoSection>
   <div className="ipoSourceBar"><span>Source: {x.source}</span><span>Fetched: {x.sourceDate||'—'}</span><span>GMP intentionally deferred</span></div>
   <button className="back" onClick={()=>navigate(kind?`/ipo/${kind}`:'/ipo')}>← Back to {kind||'all IPOs'}</button>
  </main>;
 }
 return <main className="page"><div className="pageTitle"><span>{kind?kind.toUpperCase()+' IPO':'IPO DISCOVERY'}</span><h1>{kind==='mainboard'?'Mainboard IPOs':kind==='sme'?'SME IPOs':'Indian IPOs'}</h1><p>Official NSE issue information, refreshed on the shared schedule. GMP is intentionally kept separate for a later data layer.</p></div><div className="ipoTabs"><button onClick={()=>navigate('/ipo/mainboard')}>Mainboard</button><button onClick={()=>navigate('/ipo/sme')}>SME</button><button onClick={()=>navigate('/ipo')}>All</button></div><div className="ipoGrid">{list.map(x=><IPOCard x={x} key={x.slug} navigate={navigate}/>)}</div></main>
}
function allIPOs(data){return [...data.ipo.mainboard,...data.ipo.sme]}
function Calendar({data,navigate}){const rows=allIPOs(data);return <main className="page"><div className="pageTitle"><span>CALENDAR</span><h1>IPO Calendar</h1><p>Open, close, allotment, refund, credit and listing dates.</p></div><div className="ipoTabs"><button onClick={()=>navigate('/ipo/mainboard')}>Mainboard</button><button onClick={()=>navigate('/ipo/sme')}>SME</button></div><div className="tableWrap"><table><thead><tr><th>IPO</th><th>Type</th><th>Status</th><th>Open</th><th>Close</th><th>Allotment</th><th>Listing</th><th>Price</th><th>Lot</th><th>GMP</th></tr></thead><tbody>{rows.map(x=><tr key={x.slug}><td><b>{x.name}</b><small>{x.symbol}</small></td><td>{x.type}</td><td>{x.status}</td><td>{x.open}</td><td>{x.close}</td><td>{x.allotment}</td><td>{x.listing}</td><td>{x.band}</td><td>{x.lot}</td><td>{x.gmp===null?'—':'₹'+money(x.gmp,0)}</td></tr>)}</tbody></table></div></main>}
function GMP(){return <main className="page"><div className="pageTitle"><span>SEPARATE DATA LAYER</span><h1>IPO GMP Tracker</h1><p>GMP is intentionally paused while BazaarBrief builds the official NSE-first IPO dataset. A separate unofficial GMP provider will be connected later.</p></div><div className="emptyState">Official IPO issue information is being collected independently. No GMP value is shown until the dedicated GMP feed is enabled.</div></main>}
function Allotment({data}){return <main className="page"><div className="pageTitle"><span>ALLOTMENT</span><h1>IPO Allotment Status</h1><p>Expected basis-of-allotment dates and official verification route.</p></div><div className="ipoGrid">{allIPOs(data).map(x=><div className="panel" key={x.slug}><h2>{x.name}</h2><RowText a="Status" b={x.status}/><RowText a="Allotment" b={x.allotment}/><RowText a="Refund" b={x.refund}/><RowText a="Demat credit" b={x.credit}/><RowText a="Listing" b={x.listing}/><a className="external" href="https://www.nseindia.com/check-trades-bids-verify-ipo-bids" target="_blank" rel="noreferrer">Official NSE IPO bid/allotment check ↗</a></div>)}</div></main>}

const TOOL_DEFS={
 sip:{title:'SIP Calculator',fields:[['monthly','Monthly investment (₹)',5000],['rate','Expected annual return (%)',12],['years','Investment period (years)',10]],calc:v=>{const p=Math.max(0,parseNum(v.monthly)),r=parseNum(v.rate)/1200,n=Math.max(0,parseNum(v.years))*12,fv=r? p*((Math.pow(1+r,n)-1)/r)*(1+r):p*n,invested=p*n;return [['Invested',`₹${money(invested,0)}`],['Estimated value',`₹${money(fv,0)}`],['Estimated gain',`₹${money(fv-invested,0)}`]]}},
 cagr:{title:'CAGR Calculator',fields:[['initial','Initial value (₹)',100000],['final','Final value (₹)',250000],['years','Years',5]],calc:v=>{const i=parseNum(v.initial),f=parseNum(v.final),y=parseNum(v.years);if(i<=0||f<0||y<=0)return [['CAGR','Enter positive values']];return [['CAGR',`${((Math.pow(f/i,1/y)-1)*100).toFixed(2)}%`]]}},
 average:{title:'Stock Average Calculator',fields:[['qty1','First quantity',100],['price1','First buy price (₹)',100],['qty2','Second quantity',100],['price2','Second buy price (₹)',80]],calc:v=>{const q1=Math.max(0,parseNum(v.qty1)),q2=Math.max(0,parseNum(v.qty2)),cost=q1*parseNum(v.price1)+q2*parseNum(v.price2),qty=q1+q2;return [['Total quantity',money(qty,0)],['Average price',qty?`₹${money(cost/qty)}`:'—'],['Total cost',`₹${money(cost,0)}`]]}},
 dividend:{title:'Dividend Calculator',fields:[['shares','Shares owned',100],['dividend','Dividend per share (₹)',10],['tax','Tax / withholding (%)',0]],calc:v=>{const gross=Math.max(0,parseNum(v.shares))*Math.max(0,parseNum(v.dividend)),tax=Math.max(0,parseNum(v.tax))*gross/100;return [['Gross dividend',`₹${money(gross,2)}`],['Tax',`₹${money(tax,2)}`],['Net dividend',`₹${money(gross-tax,2)}`]]}},
 pe:{title:'P/E Calculator',fields:[['price','Share price (₹)',500],['eps','EPS (₹)',25]],calc:v=>{const e=parseNum(v.eps);return [['P/E ratio',e>0?`${(parseNum(v.price)/e).toFixed(2)}x`:'—']]}},
 eps:{title:'EPS Calculator',fields:[['profit','Net profit (₹)',10000000],['shares','Weighted average shares',1000000]],calc:v=>{const s=parseNum(v.shares);return [['EPS',s>0?`₹${money(parseNum(v.profit)/s,2)}`:'—']]}},
 roe:{title:'ROE Calculator',fields:[['profit','Net profit (₹)',10000000],['equity','Average shareholders equity (₹)',50000000]],calc:v=>{const e=parseNum(v.equity);return [['ROE',e>0?`${(parseNum(v.profit)/e*100).toFixed(2)}%`:'—']]}},
 roce:{title:'ROCE Calculator',fields:[['ebit','EBIT (₹)',12000000],['capital','Capital employed (₹)',80000000]],calc:v=>{const c=parseNum(v.capital);return [['ROCE',c>0?`${(parseNum(v.ebit)/c*100).toFixed(2)}%`:'—']]}},
 marketcap:{title:'Market Cap Calculator',fields:[['price','Share price (₹)',500],['shares','Shares outstanding',10000000]],calc:v=>{const cap=parseNum(v.price)*parseNum(v.shares);return [['Market cap (₹)',`₹${money(cap,0)}`],['Market cap (₹ Cr)',`₹${money(cap/10000000,2)} Cr`]]}},
 profitgrowth:{title:'Profit Growth Calculator',fields:[['old','Previous profit (₹)',10000000],['new','Current profit (₹)',13000000]],calc:v=>{const o=parseNum(v.old);return [['Profit growth',o!==0?`${((parseNum(v.new)-o)/Math.abs(o)*100).toFixed(2)}%`:'—']]}},
 ipoinvestment:{title:'IPO Investment Calculator',fields:[['lot','Shares per lot',100],['price','IPO price per share (₹)',500],['lots','Number of lots',1]],calc:v=>{const lot=Math.max(0,parseNum(v.lot)),lots=Math.max(0,parseNum(v.lots)),inv=lot*parseNum(v.price)*lots;return [['Total shares',money(lot*lots,0)],['Investment',`₹${money(inv,0)}`]]}},
 ipoprofit:{title:'IPO Profit Calculator',fields:[['shares','Shares allotted',100],['buy','IPO price (₹)',500],['sell','Listing / sale price (₹)',650],['costs','Taxes + charges (₹)',0]],calc:v=>{const shares=Math.max(0,parseNum(v.shares)),buy=parseNum(v.buy),sell=parseNum(v.sell),costs=Math.max(0,parseNum(v.costs)),gross=(sell-buy)*shares,net=gross-costs;return [['Gross profit',`₹${money(gross,0)}`],['Costs',`₹${money(costs,0)}`],['Net profit',`₹${money(net,0)}`],['Return',buy>0?`${((sell-buy)/buy*100).toFixed(2)}%`:'—']]}},
 ipogmp:{title:'IPO GMP Calculator',fields:[['ipo','Upper price band (₹)',500],['gmp','GMP (₹)',80]],calc:v=>{const price=parseNum(v.ipo),g=parseNum(v.gmp);return [['Indicative listing price',`₹${money(price+g,2)}`],['Indicative premium',price?`${(g/price*100).toFixed(2)}%`:'—']]}},
 allotment:{title:'IPO Allotment Estimate',fields:[['applications','Applications received',100000],['lots','Lots available',5000]],calc:v=>{const a=Math.max(0,parseNum(v.applications)),l=Math.max(0,parseNum(v.lots));const p=a?Math.min(100,l/a*100):0;return [['Simple mathematical estimate',`${p.toFixed(2)}%`],['Disclaimer','Not a prediction; actual allotment follows category rules and registrar lottery/process.']]}},
 usd:{title:'USD / INR Converter',fields:[['usd','USD amount',100],['rate','USD/INR rate',96]],calc:v=>[['INR value',`₹${money(parseNum(v.usd)*parseNum(v.rate),2)}`]]},
 emi:{title:'EMI Calculator',fields:[['principal','Loan amount (₹)',1000000],['rate','Annual interest (%)',8.5],['years','Tenure (years)',10]],calc:v=>{const p=parseNum(v.principal),r=parseNum(v.rate)/1200,n=parseNum(v.years)*12;const emi=r? p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):(n?p/n:0);return [['Monthly EMI',`₹${money(emi,0)}`],['Total payment',`₹${money(emi*n,0)}`],['Total interest',`₹${money(emi*n-p,0)}`]]}},
 lumpsum:{title:'Lumpsum Calculator',fields:[['principal','Initial investment (₹)',100000],['rate','Expected annual return (%)',12],['years','Years',10]],calc:v=>{const p=parseNum(v.principal),r=parseNum(v.rate)/100,y=parseNum(v.years),fv=p*Math.pow(1+r,y);return [['Invested',`₹${money(p,0)}`],['Future value',`₹${money(fv,0)}`],['Gain',`₹${money(fv-p,0)}`]]}}
};
function Calculator({def}){const initial=Object.fromEntries(def.fields.map(([k,,v])=>[k,v]));const [v,setV]=useState(initial);useEffect(()=>setV(initial),[def.title]);const result=useMemo(()=>def.calc(v),[def,v]);return <div className="calculator"><h2>{def.title}</h2><div className="fieldGrid">{def.fields.map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="any" value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})}/></label>)}</div><div className="results">{result.map(([a,b])=><div className="resultRow" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></div>}
function Tools({tool}){const [active,setActive]=useState(tool&&TOOL_DEFS[tool]?tool:'sip');return <main><div className="pageTitle"><span>TOOLS</span><h1>Financial Tools</h1><p>Formula-based browser calculators with validation and instant results.</p></div><div className="toolSelector">{Object.entries(TOOL_DEFS).map(([k,d])=><button className={active===k?'active':''} key={k} onClick={()=>setActive(k)}>{d.title}</button>)}</div><Calculator def={TOOL_DEFS[active]}/><div className="toolNote"><b>Important:</b> calculators are mathematical tools, not investment advice. IPO GMP is unofficial; allotment estimation is not a prediction.</div></main>}
function Footer(){return <footer>BAZAAR BRIEF · Market data can be delayed. GIFT Nifty is a futures/pre-market indicator, not NIFTY 50 spot. GMP is unofficial / market-reported. Verify important figures against NSE/BSE, registrar pages and official IPO documents.</footer>}
class ErrorBoundary extends React.Component{
 constructor(props){super(props);this.state={error:null}}
 static getDerivedStateFromError(error){return {error}}
 componentDidCatch(error,info){console.error('BazaarBrief render error',error,info)}
 render(){
  if(this.state.error){
   return <><header className="appHeader"><button className="brand" onClick={()=>location.reload()}><span className="brandMark">B</span><span>BAZAAR<span>BRIEF</span></span></button><div className="marketLive"><i></i><span>APPLICATION</span><b>Error recovery</b></div></header><main className="emptyFeed"><div className="emptyFeedCard"><div className="eyebrow"><span></span>BAZAARBRIEF / RECOVERY</div><h1>The dashboard hit a rendering error.</h1><p>The application is still loaded, but a UI component failed while rendering. Reload the page to recover. No unverified market values are substituted.</p><button className="refreshBtn" onClick={()=>location.reload()}>Reload dashboard</button></div></main><Footer/></>;
  }
  return this.props.children;
 }
}
function App(){const state=useData();const [path,setPath]=useState(location.pathname.replace(/\/$/,'')||'/');const nav=p=>{history.pushState({},'',p);setPath(p);window.scrollTo({top:0,behavior:'smooth'})};useEffect(()=>{const f=()=>setPath(location.pathname.replace(/\/$/,'')||'/');addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);let content;if(!state.data){content=<main className="emptyFeed"><div className="emptyFeedCard"><div className="eyebrow"><span></span>LIVE SHARED DATA</div><h1>Waiting for the latest API refresh.</h1><p>The dashboard will display market, commodity, IPO, GMP, FII/DII and news data after the shared API feed completes successfully. Until then, no market values are shown.</p><button className="refreshBtn" onClick={()=>state.refresh(true)} disabled={state.loading}>{state.loading?'Refreshing…':'Try again'}</button></div></main>}else if(path==='/ipo')content=<IPOPage data={state.data} navigate={nav}/>;else if(path==='/ipo/mainboard')content=<IPOPage data={state.data} kind="mainboard" navigate={nav}/>;else if(path==='/ipo/sme')content=<IPOPage data={state.data} kind="sme" navigate={nav}/>;else if(path.startsWith('/ipo/mainboard/'))content=<IPOPage data={state.data} kind="mainboard" slug={path.split('/')[3]} navigate={nav}/>;else if(path.startsWith('/ipo/sme/'))content=<IPOPage data={state.data} kind="sme" slug={path.split('/')[3]} navigate={nav}/>;else if(path==='/ipo-calendar')content=<Calendar data={state.data} navigate={nav}/>;else if(path==='/gmp')content=<GMP data={state.data}/>;else if(path==='/ipo-allotment-status')content=<Allotment data={state.data}/>;else if(path.startsWith('/tools/'))content=<Tools tool={path.split('/')[2]}/>;else if(path==='/tools')content=<Tools/>;else content=<Home data={state.data} navigate={nav}/>;return <><Header state={state} onNav={nav}/>{state.msg&&<div className="notice">{state.msg}</div>}{content}<Footer/></>}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
